### ISSUE TITLE
[BUG?] Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by DoubleDBE** [mysql-net/MySqlConnector#989] opened 2021-05-16 06:04 UTC
When using the `OpenAsync` method, it works for some time.

But after a while an exception gets thrown.

I'm using `.NET Standard 2.1`

My connection string is very basic, nothing fancy:

`host=xx;port=xx;database=xx;user=xx;pwd=xx;ConvertZeroDateTime=True;AllowLoadLocalInfile=True;ConnectionTimeout=3`

```
  at MySqlConnector.Protocol.PayloadData.get_HeaderByte () [0x00000] in /_/src/MySqlConnector/Protocol/PayloadData.cs:23 
  at MySqlConnector.Core.ServerSession.ReceiveReplyAsyncAwaited (System.Threading.Tasks.ValueTask`1[TResult] task) [0x000b6] in /_/src/MySqlConnector/Core/ServerSession.cs:887 
  at System.Threading.Tasks.ValueTask`1[TResult].get_Result () [0x0001b] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corefx/src/Common/src/CoreLib/System/Threading/Tasks/ValueTask.cs:813 
  at MySqlConnector.Core.ServerSession.ConnectAsync (MySqlConnector.Core.ConnectionSettings cs, System.Int32 startTickCount, MySqlConnector.Core.ILoadBalancer loadBalancer, MySqlConnector.Protocol.Serialization.IOBehavior ioBehavior, System.Threading.CancellationToken cancellationToken) [0x00381] in /_/src/MySqlConnector/Core/ServerSession.cs:425 
  at MySqlConnector.Core.ConnectionPool.ConnectSessionAsync (System.String logMessage, System.Int32 startTickCount, MySqlConnector.Protocol.Serialization.IOBehavior ioBehavior, System.Threading.CancellationToken cancellationToken) [0x000b6] in /_/src/MySqlConnector/Core/ConnectionPool.cs:376 
  at System.Threading.Tasks.ValueTask`1[TResult].get_Result () [0x0001b] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corefx/src/Common/src/CoreLib/System/Threading/Tasks/ValueTask.cs:813 
  at MySqlConnector.Core.ConnectionPool.GetSessionAsync (MySqlConnector.MySqlConnection connection, System.Int32 startTickCount, MySqlConnector.Protocol.Serialization.IOBehavior ioBehavior, System.Threading.CancellationToken cancellationToken) [0x005c4] in /_/src/MySqlConnector/Core/ConnectionPool.cs:107 
  at MySqlConnector.Core.ConnectionPool.GetSessionAsync (MySqlConnector.MySqlConnection connection, System.Int32 startTickCount, MySqlConnector.Protocol.Serialization.IOBehavior ioBehavior, System.Threading.CancellationToken cancellationToken) [0x00812] in /_/src/MySqlConnector/Core/ConnectionPool.cs:137 
  at System.Threading.Tasks.ValueTask`1[TResult].get_Result () [0x0001b] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corefx/src/Common/src/CoreLib/System/Threading/Tasks/ValueTask.cs:813 
  at MySqlConnector.MySqlConnection.CreateSessionAsync (MySqlConnector.Core.ConnectionPool pool, System.Int32 startTickCount, System.Nullable`1[T] ioBehavior, System.Threading.CancellationToken cancellationToken) [0x00120] in /_/src/MySqlConnector/MySqlConnection.cs:863 
  at System.Threading.Tasks.ValueTask`1[TResult].get_Result () [0x0001b] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corefx/src/Common/src/CoreLib/System/Threading/Tasks/ValueTask.cs:813 
  at MySqlConnector.MySqlConnection.OpenAsync (System.Nullable`1[T] ioBehavior, System.Threading.CancellationToken cancellationToken) [0x000fa] in /_/src/MySqlConnector/MySqlConnection.cs:414 
```

**Comment by bgrainger** [comment] 2021-05-16 13:14
It looks like possibly the server is closing the connection and MySqlConnector is failing to handle the case of reading zero bytes from the connection.

**Comment by bgrainger** [comment] 2021-05-16 13:14
Would you be able to provide a packet capture (using Wireshark or similar) of this happening?

**Comment by DoubleDBE** [comment] 2021-05-16 13:59
Sure! Can i send the data somewhere private, i'd rather not have this data in the open.

**Comment by DoubleDBE** [comment] 2021-05-16 14:31
Okay never mind I captured it a different way.

This was captured using MariaDB
Server version: 10.1.36-MariaDB - mariadb.org binary distribution
Protocol version: 10

using this connection string:
`host=192.168.0.3;port=3307;database=cp;user=mama;pwd=papa;ConvertZeroDateTime=True;AllowLoadLocalInfile=True;ConnectionTimeout=3`

If this data doesn't help, let me know!

[wireshark.zip](https://github.com/mysql-net/MySqlConnector/files/6489371/wireshark.zip)

**Comment by bgrainger** [comment] 2021-05-16 15:36
AFAICT, the server sends an "Initial Handshake" packet then immediately closes the connection without warning. It's possible MySqlConnector doesn't handle this error correctly (I need to test more), but this is not a recoverable error.

**Comment by DoubleDBE** [comment] 2021-05-16 16:09
I installed the latest version of XAMPP with `MariaDB version 10.4.19` to see if it would make a difference, but the issue persist.

It even looks like the exception gets thrown immediately on the first attempt, which should give you a good direction for your tests.

I've re-captured the data in case it's helpful.

[wireshark2.zip](https://github.com/mysql-net/MySqlConnector/files/6489545/wireshark2.zip)

**Comment by bgrainger** [comment] 2021-05-16 17:25
> I've isolated the issue even more, it seems that .NET Framework and .NET Core works flawless without any issues.
> The moment when tested with .NET Standard 2.1, the issue occurs.

Can you explain what you mean by this? ".NET Standard 2.1" isn't a runtime; it's a definition of APIs that a runtime supports. What .NET implementation are you using?

I see `/Users/builder/jenkins/workspace/archive-mono/2020-02/android/` in your call stack. Is this Mono / Xamarin / Android?

**Comment by DoubleDBE** [comment] 2021-05-16 18:36
Correct. This is tested with Xamarin.Forms on an Android emulator. Could that be the culprit?

Seems strange to me because when I use `MySqlBulkCopy` (in a Xamarin.Forms project) with our cloud database, it works just fine.

I'll try to check whether something is missing in the configuration file of MariaDB on my local machine.

I'll keep you posted.

**Comment by DoubleDBE** [comment] 2021-05-17 08:57
Hi Bradley,

I have reverted to using the non-async methods in my code, which seem to solve most of my issues.
Looks like Mono is the main culprit here. Very strange.

However, I also ran some more tests that gave me weird results that may be of help.

I ran my code (again using Xamarin.Forms) on 2 different MariaDB instances that are installed on my local windows machine:

Instance 1:
Server version: 10.1.36-MariaDB - mariadb.org binary distribution
Protocol version: 10

Instance 2:
Server version: 10.4.19-MariaDB-log - mariadb.org binary distribution
Protocol version: 10

I made sure both instances ran on exactly the same `my.ini` configuration file.

Here comes the strange part:
On Instance 1 everything works as expected.
`MySqlConnection.Open()` and `MySqlBulkCopy.WriteToServer()` work great, no issues at all!

On instance 2 however, there seem to be a reoccuring issue:
Call 1 => works fine
Call 2 => Packet received out-of-order. Expected 1; got 0.
Call 3 => works fine
Call 4 => Packet received out-of-order. Expected 1; got 0.
... and it goes on and on like this...

I've captured this with wireshark in case it could be useful.
[wireshark3.zip](https://github.com/mysql-net/MySqlConnector/files/6492539/wireshark3.zip)


Here's the exception that I get:
```
  at System.Threading.Tasks.ValueTask`1[TResult].get_Result () [0x0001b] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corefx/src/Common/src/CoreLib/System/Threading/Tasks/ValueTask.cs:813 
  at MySqlConnector.Protocol.Serialization.ProtocolUtility.<DoReadPayloadAsync>g__AddContinuation|5_0 (System.Threading.Tasks.ValueTask`1[TResult] readPacketTask, MySqlConnector.Protocol.Serialization.BufferedByteReader bufferedByteReader, MySqlConnector.Protocol.Serialization.IByteHandler byteHandler, System.Func`1[TResult] getNextSequenceNumber, MySqlConnector.Protocol.Serialization.ArraySegmentHolder`1[T] previousPayloads, MySqlConnector.Protocol.Serialization.ProtocolErrorBehavior protocolErrorBehavior, MySqlConnector.Protocol.Serialization.IOBehavior ioBehavior) [0x00028] in /_/src/MySqlConnector/Protocol/Serialization/ProtocolUtility.cs:479 
  at System.Threading.Tasks.ValueTask`1[TResult].get_Result () [0x0001b] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corefx/src/Common/src/CoreLib/System/Threading/Tasks/ValueTask.cs:813 
  at MySqlConnector.Core.ServerSession.ReceiveReplyAsyncAwaited (System.Threading.Tasks.ValueTask`1[TResult] task) [0x000a6] in /_/src/MySqlConnector/Core/ServerSession.cs:884 
  at System.Threading.Tasks.ValueTask`1[TResult].get_Result () [0x0001b] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corefx/src/Common/src/CoreLib/System/Threading/Tasks/ValueTask.cs:813 
  at MySqlConnector.Core.ServerSession.TryPingAsync (System.Boolean logInfo, MySqlConnector.Protocol.Serialization.IOBehavior ioBehavior, System.Threading.CancellationToken cancellationToken) [0x000de] in /_/src/MySqlConnector/Core/ServerSession.cs:803 
  at System.Threading.Tasks.ValueTask`1[TResult].get_Result () [0x0001b] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corefx/src/Common/src/CoreLib/System/Threading/Tasks/ValueTask.cs:813 
  at MySqlConnector.Core.ConnectionPool.GetSessionAsync (MySqlConnector.MySqlConnection connection, System.Int32 startTickCount, MySqlConnector.Protocol.Serialization.IOBehavior ioBehavior, System.Threading.CancellationToken cancellationToken) [0x003c8] in /_/src/MySqlConnector/Core/ConnectionPool.cs:75 
  at MySqlConnector.Core.ConnectionPool.GetSessionAsync (MySqlConnector.MySqlConnection connection, System.Int32 startTickCount, MySqlConnector.Protocol.Serialization.IOBehavior ioBehavior, System.Threading.CancellationToken cancellationToken) [0x00812] in /_/src/MySqlConnector/Core/ConnectionPool.cs:137 
  at System.Threading.Tasks.ValueTask`1[TResult].get_Result () [0x0001b] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corefx/src/Common/src/CoreLib/System/Threading/Tasks/ValueTask.cs:813 
  at MySqlConnector.MySqlConnection.CreateSessionAsync (MySqlConnector.Core.ConnectionPool pool, System.Int32 startTickCount, System.Nullable`1[T] ioBehavior, System.Threading.CancellationToken cancellationToken) [0x00120] in /_/src/MySqlConnector/MySqlConnection.cs:863 
  at System.Threading.Tasks.ValueTask`1[TResult].get_Result () [0x0001b] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/external/corefx/src/Common/src/CoreLib/System/Threading/Tasks/ValueTask.cs:813 
  at MySqlConnector.MySqlConnection.OpenAsync (System.Nullable`1[T] ioBehavior, System.Threading.CancellationToken cancellationToken) [0x000fa] in /_/src/MySqlConnector/MySqlConnection.cs:414 
  at MySqlConnector.MySqlConnection.Open () [0x00000] in /_/src/MySqlConnector/MySqlConnection.cs:380 
```

**Comment by bgrainger** [comment] 2021-06-14 21:11
Closing, because this seems like a bug in the runtime, not a bug in MySqlConnector itself.

**Closed by bgrainger** 2021-06-14 21:11 UTC
