### ISSUE TITLE
System.TypeLoadException: Field 's_setNamesUtf8Payload' has an invalid type.

### ISSUE THREAD

**Issue by ArseeniK** [mysql-net/MySqlConnector#767] opened 2020-01-30 09:35 UTC
Hello, i have the current error when i'm attepting to open a db connection:

`System.TypeLoadException: Field 's_setNamesUtf8Payload' has an invalid type.
at MySql.Data.MySqlClient.MySqlConnection.Dispose (System.Boolean disposing) [0x00003] in <979ffe2c2da043ff9c86d2f430106524>:0
  at System.ComponentModel.Component.Dispose () [0x00000] in <ae22a4e8f83c41d69684ae7f557133d9>:0
`

Using MySQLConnector v0.61.0
Linux vps554313 4.9.0-8-amd64 #1 SMP Debian 4.9.144-3.1 (2019-02-19) x86_64 GNU/Linux
Mono JIT compiler version 5.20.1.19 (tarball Thu Apr 11 09:07:22 UTC 2019)

**Comment by bgrainger** [comment] 2020-01-30 15:10
I don't test with Mono, but I would guess this is a bug/incompatibility with Mono 5.20 (which is an older version).

Can you run with .NET Core or a newer version of Mono?

**Comment by ArseeniK** [comment] 2020-01-31 10:07
Hello, thanks for this quick answer.

I updated mono (v6.8.0.96) and this error is gone.
Btw, i have a new one :

`System.TypeLoadException: Could not find method due to a type load error
  at MySql.Data.MySqlClient.MySqlConnection+<OpenAsync>d__25.MoveNext () [0x000f0] in <979ffe2c2da043ff9c86d2f430106524>:0
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <437ba245d8404784b9fbab9b439ac908>:0
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <437ba245d8404784b9fbab9b439ac908>:0
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <437ba245d8404784b9fbab9b439ac908>:0
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <437ba245d8404784b9fbab9b439ac908>:0
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <437ba245d8404784b9fbab9b439ac908>:0
  at MySql.Data.MySqlClient.MySqlConnection.Open () [0x00017] in <979ffe2c2da043ff9c86d2f430106524>:0`

**Comment by bgrainger** [comment] 2020-01-31 15:13
Since this code works with .NET Framework and .NET Core 2.0/3.0, this may be a bug you need to report against the Mono project. I can't tell what the problem is from the call stack, but `TypeLoadException` seems like a runtime problem.

**Comment by bgrainger** [comment] 2020-02-08 17:12
Closing as external.

**Closed by bgrainger** 2020-02-08 17:12 UTC
Labels: invalid
