### ISSUE TITLE
System.TypeLoadException: Field 's_setNamesUtf8Payload' has an invalid type

### ISSUE THREAD

**Issue by SERBice** [mysql-net/MySqlConnector#959] opened 2021-03-19 01:24 UTC
Hi, anyone known why I get this error when I try to use the mySqlConnector. I'm using it on FiveM (FX Server) enviroment:

Error code:
```
System.TypeLoadException: Field 's_setNamesUtf8Payload' has an invalid type.
  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder1[TResult].Start[TStateMachine] (TStateMachine& stateMachine) [0x0002c] in <fbc4ec45371543bfba3678ebb82caf6d>:0
  at System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder1[TResult].Start[TStateMachine] (TStateMachine& stateMachine) [0x00000] in <a0fea0943f984048a442056f03888c06>:0
  at MySqlConnector.MySqlConnection.CreateSessionAsync (MySqlConnector.Core.ConnectionPool pool, System.Int32 startTickCount, System.Nullable1[T] ioBehavior, System.Threading.CancellationToken cancellationToken) [0x0003d] in <5c33f05042324aeaba5b043b99b8ddd7>:0
  at MySqlConnector.MySqlConnection.OpenAsync (System.Nullable1[T] ioBehavior, System.Threading.CancellationToken cancellationToken) [0x000d1] in <5c33f05042324aeaba5b043b99b8ddd7>:0
  at seus_server.seusServer.testConn () [0x000a8] in <8c1943973eed45b49f23b9b3c646564c>:0
```

My code is:
```
        private async Task testConn()
        {
            string connStr = "server=localhost;user=admin;database=server;port=3306;password=password";
            Debug.WriteLine($"ChatStoreServer: >> Connecting to the database");

            MySqlConnection conn = new MySqlConnection(connStr);

            try
            {
                await conn.OpenAsync();

                string testSQL = "SELECT count(0) from licenses";
                MySqlCommand command = new MySqlCommand(testSQL, conn);

                long messagesNo = (long)await command.ExecuteScalarAsync();

                Debug.WriteLine($"ChatStoreServer: >> Total messages stored in database: {messagesNo} ");

            }
            catch (Exception ex)
            {
                Debug.WriteLine($"ChatStoreServer: >> {ex} ");
            }

            conn.Close();

            Debug.WriteLine($"ChatStoreServer: >> Disconnected");
        }
        ```

**Comment by SERBice** [comment] 2021-03-19 01:30
Under .net core enviroment this work fine (an console app in windows) .

**Comment by bgrainger** [comment] 2021-03-19 02:19
I haven't heard of FiveM; is it a .NET runtime?

I don't understand why `static readonly PayloadData s_setNamesUtf8mb4Payload = QueryPayload.Create("SET NAMES utf8mb4 COLLATE utf8mb4_bin;");` would "[have] an invalid type".

If that's truly the problem, you would have to go back to before https://github.com/mysql-net/MySqlConnector/commit/e95d80fe810522a46f4655dfbf40552a9b9440b3 (i.e., version 0.36.0) before that code was introduced.

**Comment by bgrainger** [comment] 2021-03-19 02:20
Closing as this code works as intended on all supported .NET runtimes (.NET Framework & .NET Core; probably also Mono and Xamarin based on SO posts).

**Closed by bgrainger** 2021-03-19 02:20 UTC
