### ISSUE TITLE
Object cannot be cast from DBNull to other types when conn.open

### ISSUE THREAD

**Issue by yucikala** [mysql-net/MySqlConnector#1322] opened 2023-05-17 07:56 UTC
**Software versions**
MySqlConnector version:  2.2.6
Server type (MySQL, MariaDB, Aurora, etc.) and version:  10.11.2-MariaDB-log
.NET version:  .NET 5.0

**Describe the bug**
When program try to connect, It crash... ("Object cannot be cast from DBNull to other types."

**Exception**
"Object cannot be cast from DBNull to other types."

   at System.DBNull.System.IConvertible.ToInt32(IFormatProvider provider)
   at MySql.Data.MySqlClient.Driver.LoadCharacterSets(MySqlConnection connection)
   at MySql.Data.MySqlClient.Driver.Configure(MySqlConnection connection)
   at MySql.Data.MySqlClient.MySqlConnection.Open()
   at MysqlBackup.Program.ProcessServerExport(ConfigExclude excludeConfig, Server server) in D:\Projekty\smallprograms\MysqlBackup\Program.cs:line 145
   at MysqlBackup.Program.Execute(Options opts) in D:\Projekty\smallprograms\MysqlBackup\Program.cs:line 90

**Code sample**
//connstring is with example values
 constring = "server=myserver;Port=3306;user=userlogin;pwd=\"=password123456\";database=dbName;convertzerodatetime=true;";
            using (var conn = new MySqlConnection(constring))
            {
                using (var cmd = new MySqlCommand())
                {
                    using (var mb = new MySqlBackup(cmd))
                    {
                        cmd.Connection = conn;
                        cmd.CommandTimeout = 99999;
                        conn.Open(); //here is the problem

```csharp
/* A concise code sample to reproduce the bug */
```

**Expected behavior**
Normal connection. To other databases is ok, but i have one, where is problem.

**Comment by yucikala** [comment] 2023-05-17 09:24
I have other info. 
Problem is, that mysql server return null ID of collation.

If you reda this: https://jira.mariadb.org/browse/MDEV-27009, thay want to remove this columns

**Comment by bgrainger** [comment] 2023-05-17 13:46
A bug in `MySql.Data.MySqlClient.Driver.LoadCharacterSets` is a problem with Oracle's MySQL Connector/NET driver. This is a duplicate of https://bugs.mysql.com/bug.php?id=109331. As you can see on that bug report, they do not plan to fix the issue.

This repo is for MySqlConnector, a different library that doesn't exhibit that bug. I strongly recommend switching from MySql.Data to MySqlConnector. See more information here: https://mysqlconnector.net/tutorials/migrating-from-connector-net/.

**Closed by bgrainger** 2023-05-17 13:46 UTC
