### ISSUE TITLE
TLS Error While Connecting to MySQL 5.6

### ISSUE THREAD

**Issue by random7192** [mysql-net/MySqlConnector#927] opened 2021-01-14 20:32 UTC
I upgraded to dot net core 5.0 .

I am connecting to Mysql on RDS. From visual studio everything works fine.

But from docker image i get a connection error SSL Handshake failed with OpenSSL error

Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL. ---> Interop+Crypto+OpenSslCryptographicException: error:1421C105:SSL routines:set_client_ciphersuite:wrong cipher returned --- End of inner exception stack trace --- at Interop.OpenSsl.DoSslHandshake(SafeSslHandle context, ReadOnlySpan1 input, Byte[]& sendBuf, Int32& sendCount)
at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteSslContext& context, ReadOnlySpan1 inputBuffer, Byte[]& outputBuffer, SslAuthenticationOptions sslAuthenticationOptions) --- End of inner exception stack trace --- at MySql.Data.Common.Ssl.StartSSL(Stream& baseStream, Encoding encoding, String connectionString) at MySql.Data.MySqlClient.NativeDriver.Open() at MySql.Data.MySqlClient.Driver.Open() at MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings) at MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection() at MySql.Data.MySqlClient.MySqlPool.GetPooledConnection() at MySql.Data.MySqlClient.MySqlPool.TryToGetDriver() at MySql.Data.MySqlClient.MySqlPool.GetConnection() at MySql.Data.MySqlClient.MySqlConnection.Open()

My Docker image is using the below base image

`FROM mcr.microsoft.com/dotnet/aspnet:5.0-alpine AS base

WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build`

**Comment by bgrainger** [comment] 2021-01-15 04:10
A) This is the repository for MySqlConnector. You're using MySql.Data; bugs can be reported at https://bugs.mysql.com/

B) This is a duplicate of https://github.com/mysql-net/MySqlConnector/issues/904. To fix it, switch from MySql.Data to MySqlConnector and add `;TlsCipherSuites=TLS_DHE_RSA_WITH_AES_256_GCM_SHA384` (specifying additional cipher suites as necessary) to your connection string.

**Closed by bgrainger** 2021-01-15 04:10 UTC
