### ISSUE TITLE
Exception in ConnectionPool: An item with the same key has already been added

### ISSUE THREAD

**Issue by usenff-cu** [mysql-net/MySqlConnector#1245] opened 2022-11-30 15:44 UTC
**Software versions**
MySqlConnector version: 2.1.10
Server type and version: MySQL 8.0.28
.NET version: net6.0
ORM NuGet packages and versions: linq2db 4.1.1

**Describe the bug**
In our production environment we get the exception below mutliple times per day. Multiple exceptions are thrown at the same time then it can be quite for hours. So far we have no way to reproduce it. See attached log for additional context. The first exception is logged at line 267.

**Exception**

```
System.ArgumentException: An item with the same key has already been added. Key: 1.811
    at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
    at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int32 startTickCount, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 126
    at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, Int32 startTickCount, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 126
    at MySqlConnector.MySqlConnection.CreateSessionAsync(ConnectionPool pool, Int32 startTickCount, Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 948
    at MySqlConnector.MySqlConnection.OpenAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 455
    at LinqToDB.Data.DataConnection.EnsureConnectionAsync(CancellationToken cancellationToken)
    at LinqToDB.Linq.ExpressionQuery`1.StartLoadTransactionAsync(Query query, CancellationToken cancellationToken)
    at LinqToDB.Linq.ExpressionQuery`1.LinqToDB.Async.IQueryProviderAsync.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
    at Nop.Services.Customers.CustomerService.<>c__DisplayClass33_0.<<GetCustomerByGuidAsync>b__2>d.MoveNext() in /src/Libraries/Nop.Services/Customers/CustomerService.cs:line 499
 --- End of stack trace from previous location ---
    at Nop.Core.Caching.PerRequestCache.GetAsync[T](String key, Func`1 acquire) in /src/Libraries/Nop.Core/_CU/Caching/PerRequestCache.cs:line 110
    at Nop.Core.Caching.MemoryCacheManager.GetAsync[T](CacheKey key, Func`1 acquire, Int32 overwriteCacheTime) in /src/Libraries/Nop.Core/Caching/MemoryCacheManager.cs:line 169
    at Nop.Services.Customers.CustomerService.GetCustomerByGuidAsync(Guid customerGuid) in /src/Libraries/Nop.Services/Customers/CustomerService.cs:line 514
    at Nop.Web.Framework.WebWorkContext.SetCurrentCustomerAsync(Customer customer) in /src/Presentation/Nop.Web.Framework/WebWorkContext.cs:line 731
    at Nop.Web.Framework.WebWorkContext.GetCurrentCustomerAsync() in /src/Presentation/Nop.Web.Framework/WebWorkContext.cs:line 603
    at Nop.Web._CU.ActionFilters.GlobalActionFilter.CheckForPwChangeAsync(ActionExecutingContext context) in /src/Presentation/Nop.Web/_CU/ActionFilters/GlobalActionFilter.cs:line 71
    at Nop.Web._CU.ActionFilters.GlobalActionFilter.OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next) in /src/Presentation/Nop.Web/_CU/ActionFilters/GlobalActionFilter.cs:line 43
    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
    at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
    at Nop.Services.Authentication.AuthenticationMiddleware.InvokeAsync(HttpContext context) in /src/Libraries/Nop.Services/Authentication/AuthenticationMiddleware.cs:line 102
    at StackExchange.Profiling.MiniProfilerMiddleware.Invoke(HttpContext context) in C:\projects\dotnet\src\MiniProfiler.AspNetCore\MiniProfilerMiddleware.cs:line 121
    at WebMarkupMin.AspNetCore6.WebMarkupMinMiddleware.ProcessAsync(HttpContext context, Boolean useMinification, Boolean useCompression)
    at WebMarkupMin.AspNetCore6.WebMarkupMinMiddleware.ProcessAsync(HttpContext context, Boolean useMinification, Boolean useCompression)
    at WebMarkupMin.AspNetCore6.WebMarkupMinMiddlewareBase.Invoke(HttpContext context)
    at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
    at Nop.Services.Common.KeepAliveMiddleware.InvokeAsync(HttpContext context, IWebHelper webHelper) in /src/Libraries/Nop.Services/Common/KeepAliveMiddleware.cs:line 52
    at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[Exception] @ 2022-11-30T11:43:20.0495257+00:00
       => SpanId:096218f1c8bd40d7, TraceId:4d79e6fe9eb6fa84a148375c8d3b2aa3, ParentId:0000000000000000 => ConnectionId:0HMMIN7K38K5E => RequestPath:/api/products RequestId:0HMMIN7K38K5E:0000004B
       An exception was thrown attempting to execute the error handler.
```

**Expected behavior**
No exception during connection-handling.

**Additional context**
For additional context see attached "20221130-mysqlconnector-00.log". It contains debug-information of MySqlConnector and all application-exceptions:
[20221130-mysqlconnector-00.log](https://github.com/mysql-net/MySqlConnector/files/10124745/20221130-mysqlconnector-00.log)

**Comment by bgrainger** [comment] 2022-11-30 22:09
I can't understand the state that's in the log. My assumption is that the dictionary with duplicate keys is `m_leasedSessions`. This is modified (under a lock) when sessions are created or returned. The exception is `System.ArgumentException: An item with the same key has already been added. Key: 1.811`.

However, this exception is the only time that `1.811` appears in this file. My expectation would be that I would also see log lines for when the session was initially created, returned to a client, returned to the pool, etc. With no other context, I don't know how the pool got in this state.

However, I do see some log lines that may indicate incorrect use of MySqlConnector:

```
warn: MySqlConnector.ConnectionPool[0] @ 2022-11-30T10:06:46.2060987+00:00
      Pool1: RecoveredSessionCount=10
warn: MySqlConnector.ConnectionPool[0] @ 2022-11-30T10:07:46.2066205+00:00
      Pool1: RecoveredSessionCount=4
...
dbug: MySqlConnector.ConnectionPool[0] @ 2022-11-30T14:27:46.4095180+00:00
      Pool1 found Session1.2626 to clean up
dbug: MySqlConnector.ServerSession[0] @ 2022-11-30T14:27:46.4095620+00:00
      Session1.2626 closing stream/socket
dbug: MySqlConnector.ConnectionPool[0] @ 2022-11-30T14:27:46.4096661+00:00
      Pool1 found Session1.2375 to clean up
dbug: MySqlConnector.ServerSession[0] @ 2022-11-30T14:27:46.4097047+00:00
      Session1.2375 closing stream/socket
```

The pool appears to be finding leaked sessions. I suspect you may be creating but not disposing `MySqlConnection` objects. This causes them to not be returned to the pool once they've finished being used, which means the pool has to find and recover these leaked objects. It also means that an open connection can't be reused (until it's recovered) and a new one needs to be created instead. Please ensure that all created `MySqlConnection` objects are disposed.

Additionally, over 2,000 sessions were created during the 4.5 hour period covered by the log files. This indicates inefficient use of pooled connections. As long as there's a steady state of incoming requests, I would expect the same handful of pooled connections to be reused over and over. This might not be the case if there are bursts of 100s of connections in a short period of time followed by minutes or hours of inactivity; in that case, MySqlConnector will prune the idle connections (to save server resources) and recreate them all again on the next burst. Check that `ConnectionLifeTime` isn't set too low, and consider raising `ConnectionIdleTimeout` for your use case.

**Comment by bgrainger** [comment] 2022-11-30 22:11
The log file was helpful; thank you. I may need to see it created with "Trace" level logging enabled, and from the very beginning of the application.

**Comment by usenff-cu** [comment] 2022-12-01 12:28
Thank you for the quick response. I was also confused, that I don't see the key `1.811` multiple times in the log. The log should contain every entry from the startup of the application.

I will try to provide trace-logs next week.

Regarding the leaked sessions we will check if there is a problem in the shop-framework we are using or if we introduced a bug with our customizations.

**Comment by bgrainger** [comment] 2022-12-22 18:29
This bug might be caused by https://github.com/mysql-net/MySqlConnector/issues/1263.

If `RecoverLeakedSessionsAsync` runs twice (which definitely seems to be happening in this log), then the same session might be placed on `m_sessions` twice. Two separate threads might pull it off and then call `m_leasedSessions.Add(session.Id, session);`, which would throw this exception.

**Comment by bgrainger** [comment] 2022-12-22 20:38
Duplicate of https://github.com/mysql-net/MySqlConnector/issues/1263

**Closed by bgrainger** 2022-12-22 20:38 UTC
Labels: waiting for answer
