### ISSUE TITLE
Cannot update items in database through Dapper + MySqlConnector

### ISSUE THREAD

**Issue by xavierpena** [mysql-net/MySqlConnector#44] opened 2016-09-07 07:55 UTC
I have tested two of my models with the same result. Here is the exception for one of the models:

Result Message:

```
System.NullReferenceException: Object reference not set to an instance of an object.
```

Result StackTrace:  

```
at MySql.Data.MySqlClient.MySqlDataReader.get_FieldCount()
   at Dapper.SqlMapper.GetColumnHash(IDataReader reader, Int32 startBound, Int32 length)
   at Dapper.SqlMapper.<QueryImpl>d__125`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType)
   at DbManager.Data.Repositories.StationRepository.Update(Station station) in E:\svn-edric\ProofOfConcept\DbManager\DbManager.Data\Repositories\StationRepository.cs:line 70
   at DbManager.Tests.SqlConnectorTests.SqlConnector_UpdateItem() in E:\svn-edric\ProofOfConcept\DbManager\DbManager.Tests\SqlConnectorTests.cs:line 67
```

Sql query string:   

```
"UPDATE stations SET name=@name,stationType_SID=@stationType_SID,geoPosition_SID=@geoPosition_SID,service_start=@service_start,service_end=@service_end,deleted=@deleted,created_on=@created_on,externalWebsite=@externalWebsite,externalTitle=@externalTitle WHERE SID=@SID"
```

Dapper execution:

```
_db.Query<Station>(queryString, station);
```

Model:

```
public class Station
{
    public ulong? SID { get; set; }
    public string name { get; set; }
    public ulong stationType_SID { get; set; }
    public ulong? geoPosition_SID { get; set; }
    public DateTime? service_start { get; set; }
    public DateTime? service_end { get; set; }
    public bool? deleted { get; set; }
    public DateTime created_on { get; set; }
    public string externalWebsite { get; set; }
    public string externalTitle { get; set; }
}   
```

**Comment by bgrainger** [comment] 2016-09-07 13:49
The query string isn't selecting any columns; this will always fail.

With the official connector, this will produce the exception:

```
    SideBySide.UpdateTests.UpdateDapperModel [FAIL]
      System.InvalidOperationException : No columns were selected
      Stack Trace:
        D:\Dev\dapper-dot-net\Dapper NET40\SqlMapper.cs(3724,0): at Dapper.SqlMapper.GetTypeDeserializer(Type type, IDataReader reader, Int32 startBound, Int32 length, Boolean returnNullIfFirstMissing)
        D:\Dev\dapper-dot-net\Dapper NET40\SqlMapper.cs(2229,0): at Dapper.SqlMapper.GetDeserializer(Type type, IDataReader reader, Int32 startBound, Int32 length, Boolean returnNullIfFirstMissing)
        D:\Dev\dapper-dot-net\Dapper NET45\SqlMapperAsync.cs(101,0): at Dapper.SqlMapper.<QueryAsync>d__147`1.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
        tests\SideBySide.New\UpdateTests.cs(174,0): at SideBySide.UpdateTests.<UpdateDapperModel>d__6.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  Finished:    SideBySide.Baseline
```

In this connector, it produces a different exception (the one you reported in the issue):

```
      System.NullReferenceException : Object reference not set to an instance of an object.
      Stack Trace:
        C:\Code\Projects\MySqlConnector\src\MySqlConnector\MySqlClient\MySqlDataReader.cs(286,0): at MySql.Data.MySqlClient.MySqlDataReader.get_FieldCount()
           at Dapper.SqlMapper.GetColumnHash(IDataReader reader, Int32 startBound, Int32 length)
           at Dapper.SqlMapper.<QueryAsync>d__23`1.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
        C:\Code\Projects\MySqlConnector\tests\SideBySide.New\UpdateTests.cs(175,0): at SideBySide.UpdateTests.<UpdateDapperModel>d__6.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
```

(This should be fixed to produce the same Dapper exception; I will leave this issue open to address that.)

You can fix your code in one of two ways:

1. Change `Query<Station>(queryString, station)` to `Execute(queryString, station)`
2. Append `; select * from stations where SID=@SID;` to `queryString`

**Comment by xavierpena** [comment] 2016-09-07 13:58
I see, thanks a lot.

The same Dapper code was working OK when using the Oracle connector instead of this MySqlConnector. This is why I wrongly presumed that it was an error of the connector.

I guess Dapper prefers not to be too strict on that one, and they let it pass if you use Query when you should have used Execution. The change in the connector exception is what got Dapper confused.

**Closed** 2016-09-07 14:00 UTC
Labels: up for grabs

**Comment by bgrainger** [comment] 2016-09-07 14:01
I haven't used the Oracle connector, so I could only speculate about why `Query` succeeds for it, but not MySQL. But based on my experience with MySQL and SQL Server, I would call this the expected behaviour (it's part of the reason for both `Execute` and `Query` to exist as separate methods).
