### ISSUE TITLE
Unable to set connection timeout for each link for multi-server failover

### ISSUE THREAD

**Issue by Flithor** [mysql-net/MySqlConnector#1527] opened 2024-11-29 08:32 UTC
Just try this code:
```
using var conn = new MySqlConnection("Server=1.1.1.1,1.1.1.2,127.0.0.1;");
conn.Open();
```
Will got "Connect Timeout expired." exception.

Because each tcp connection will try over 20 seconds but there ware default connection timeout is 30 seconds, The first two invalid host will cause timeout and never try the third host.
There is no way to set the timeout for each try now.

Set `ConnectionTimeout=60` can temporarily work around the problem, but it wastes too much time.

**Comment by bgrainger** [comment] 2024-11-29 21:55
Duplicate of #556

**Closed by bgrainger** 2024-11-29 21:55 UTC
