### ISSUE TITLE
work well under the IL2CPP ARM64,but connect fail under the IL2CPP ARMv8 (Unity3D)

### ISSUE THREAD

**Issue by BoysheO** [mysql-net/MySqlConnector#1107] opened 2021-12-27 11:11 UTC
**Software versions**
MySqlConnector version:2.1.2
Server type (MySQL, MariaDB, Aurora, etc.) and version: MySQL
.NET version: Unity3D 2020.3.22f1

**Describe the bug**
When I build IL2CPP ARM64 apk,the code wokd well on Android Phone.When I build IL2CPP ARMv8 apk,the code report "2021/12/27 19:09:26.510 26506 26530 Info Unity Unable to connect to any of the specified MySQL hosts.".

**Code sample**
*ALL of the personal information in the code are not important。192.168.50.250 is my local ip.

```csharp

        string str= "server= 192.168.50.250;port=3306;user=root;password=123456;Database=pixelMapLog;SslMode = none;";
        MySqlConnection conn = new MySqlConnection(str);
        try
        {
            conn.Open();
            Debug.Log("open!");
            MySqlCommand cmd = new MySqlCommand("SELECT * FROM log where id=10 LIMIT 1;", conn);
            MySqlDataReader reader = cmd.ExecuteReader();
            reader.Read();
            Debug.Log(reader["id"]);
        }
        catch (MySqlException ex)
        {
            Debug.Log(ex.Message);
        }
        finally
        {
            conn.Close();
        }
```

**Comment by bgrainger** [comment] 2021-12-27 21:58
This seems like it could be a problem with the IL2CPP toolchain, or with TCP/IP connectivity in ARMv8 (sockets? firewall?).

Since MySqlConnector is unchanged in the working and the not working scenario, it seems plausible that the problem is elsewhere. Closing this issue until more concrete evidence of a problem in MySqlConnector is provided.

**Closed by bgrainger** 2021-12-27 21:58 UTC
