### ISSUE TITLE
Consider removing out of support TFMs #287

### ISSUE THREAD

**Issue by ViktorHofer** [mysql-net/MySqlConnector#972] opened 2021-04-21 21:14 UTC
From the README.md:

> .NET Standard support: It must run on the full .NET Framework and all platforms supported by .NET Core.

Most libraries already target .NET Standard 2.0 or a supported platform that support .NET Standard 2.0 like

- .NET Core 2.0 and above
- .NET Framework 4.6.1 and above
- UAP10.0.16299

I would suggest to consider dropping support for .NET Standard 1.3 and older .NET Framework versions in favor of a broader API set and a simplified dependency graph. Other open source repositories are dropping support for older targets as well, i.e. xunit v3. I would be willing to send a PR but wanted to open an issue to discuss this first.

**Comment by bgrainger** [comment] 2021-04-21 21:41
Duplicate of https://github.com/mysql-net/MySqlConnector/issues/636; let's move discussion there.

**Closed by bgrainger** 2021-04-21 21:41 UTC
Labels: duplicate

**Comment by bgrainger** [comment] 2021-04-21 21:53
I think I see a trend here... any particular reason why this is an important issue for MySqlConnector?

![image](https://user-images.githubusercontent.com/188129/115625689-47a77500-a2b1-11eb-82fd-c311d2d66c02.png)

**Comment by bgrainger** [comment] 2021-10-04 13:39
Duplicate of #636
