### ISSUE TITLE
MacOS Big Sur: Interop+AppleCrypto+SslException

### ISSUE THREAD

**Issue by sherloqholmes** [mysql-net/MySqlConnector#908] opened 2020-11-24 14:25 UTC
Hi,

Since the launch of OSX Big Sur we are getting the following error while trying to connect to a Google Cloud SQL MySQL Database (MySQL 5.7).

When connecting to a Database running on Azure DB for MySQL (MySQL 8) we don't see this problem.
In both cases we are using the latest stable release of Pomelo EF Core for MySQL that supports .NET 3.1

I have also tested this with the latest version of MySQL Connector and was able to reproduce this issue.
I do have a simple project that can reproduce this issue, but since this issue only occurs on Google Cloud SQL I can't share the connection string here.

```MySql.Data.MySqlClient.MySqlException (0x80004005): SSL Authentication Error
 ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> Interop+AppleCrypto+SslException: Internal error
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslStream.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__64_2(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at MySqlConnector.Core.ServerSession.InitSslAsync(ProtocolCapabilities serverCapabilities, ConnectionSettings cs, SslProtocols sslProtocols, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ServerSession.cs:line 1268
   at MySqlConnector.Core.ServerSession.InitSslAsync(ProtocolCapabilities serverCapabilities, ConnectionSettings cs, SslProtocols sslProtocols, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ServerSession.cs:line 1295
   at MySqlConnector.Core.ServerSession.ConnectAsync(ConnectionSettings cs, ILoadBalancer loadBalancer, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ServerSession.cs:line 399
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ConnectionPool.cs:line 112
   at MySqlConnector.Core.ConnectionPool.GetSessionAsync(MySqlConnection connection, IOBehavior ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ConnectionPool.cs:line 141
   at MySql.Data.MySqlClient.MySqlConnection.CreateSessionAsync(ConnectionPool pool, Nullable`1 ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 645
   at MySql.Data.MySqlClient.MySqlConnection.OpenAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 312
```

**Comment by bgrainger** [comment] 2020-11-24 23:30
> In both cases we are using the latest stable release of Pomelo EF Core for MySQL that supports .NET 3.1

Are you using MySqlConnector 0.69.10 for that, or some other version?

> I have also tested this with the latest version of MySQL Connector and was able to reproduce this issue.

Does that mean v1.1.0 (and just a simple connection, not with Pomelo)?

I wonder if the default ciphers in Big Sur changed, similar to #904? If so, the same workaround could be used. I don't have a Mac (or Big Sur) for testing, though.

**Comment by sherloqholmes** [comment] 2020-11-25 08:19
Hi,

Yes we tested with both MySqlConnector 0.69.10 and 1.1.0 both with pomelo.
However, while testing with Mysql.data we are observing the same behaviour, it must be a system level issue, but right now I don't have any other clues.

We have tried most of the steps in #904 but haven't tried the latest beta. Will do that today.
I will also open up an issue in the .NET repo since it seems to be unrelated to MySqlConnector - still open for suggestions.

**Comment by SumBeam** [comment] 2020-11-25 09:20
Hi!

I work together with @sherloqholmes and I digged a bit further into this issue.

So the server accepts these cipher suites:
```
SHOW GLOBAL VARIABLES where variable_name = 'ssl_cipher'

Result:
ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA
```
I downloaded the code yesterday and used the compiled DLL in our test project.
For example, when I use the first cipher suite in the connection string, it returns a different error: _Interop+AppleCrypto+SslException: handshake failure_

`Server=xxx;uid=xxx;pwd=xxx;Convert Zero Datetime=true;Max Pool Size=100;SSL Mode=Required;tlsversion=TLSv1.2;TlsCipherSuites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256`


Applications like MySQLWorkbench, Sequel Ace or the mysql command line are working fine.

So yeah, I agree that it doesn't look like it is an issue with this package, but an .NET / Big Sur change...

@bgrainger You mentioned something about 'If default ciphers in Big Sur changed'. Do you know how we can test that? I'm happy to help with some testing on my machine.

**Comment by bgrainger** [comment] 2020-11-26 05:17
I do think that opening an issue on the dotnet repo is worth doing, to get some more eyes on the problem (since it's not specific to just MySqlConnector).

I don't know what the current state of crypto on macOS is.

* https://github.com/dotnet/announcements/issues/21 says it uses Apple Security Framework on macOS
* https://github.com/dotnet/docs/issues/16696 says it uses OpenSSL 1.1.x

Maybe one or the other had a change to some defaults in Big Sur? I don't know enough about the specific implementation details to even know where to start looking.

**Comment by SumBeam** [comment] 2020-12-06 12:30
We ended up in regenerating the SSL certificates for the GCP databases. Somehow the certificate was not fully trusted by Big Sur and dotnet could not connect to it (but applications like MySQL Workbench/Sequel Ace were).

With the new certificates the issue is solved and it is now working fine!

Thanks for the suggestions! :) I think we can close this issue

**Closed** 2020-12-06 17:38 UTC

**Comment by kocburak** [comment] 2020-12-14 07:25
Hi,

Generating new CA, Client Key and Certificate didn't worked for me. 

MySQL version: 5.7.14
Operating system: Mac OS Big Sur
MysqlConnector: 1.1.0 and 0.69.10

**Comment by bgrainger** [comment] 2020-12-14 17:55
I don't have a Mac, so I can't troubleshoot this issue myself. I suggest trying to create a [minimal complete repro](https://stackoverflow.com/help/minimal-reproducible-example) using `SslStream.AuthenticateAsClient(Async)` on macOS.

Assuming you need a Google Cloud SQL MySQL Server to reproduce the bug, you'll need to write a small amount of code that opens a TCP connection, receives an Initial Handshake packet, responds with a SSL Request Packet, then negotiates SSL: https://dev.mysql.com/doc/internals/en/ssl.html

If that fails, then since no MySqlConnector code is involved, and no SQL auth is needed (just a public endpoint on port 3306), it should be easy (I hope) to write up an example that could be posted to the dotnet repo.

**Comment by bgrainger** [comment] 2020-12-14 19:17
@kocburak Here's some sample code you can run on your Mac. If this fails, it really seems like it's a Big Sur + .NET Core problem:

```csharp
// connect to server
using var tcpClient = new TcpClient();
tcpClient.Connect("YOUR GOOGLE SQL PUBLIC IP ADDRESS", 3306);
using var stream = tcpClient.GetStream();

// read initial handshake (sent from server)
var initialHandshake = new byte[200];
stream.Read(initialHandshake, 0, initialHandshake.Length);

// send SSL request
var sslRequest = new byte[36];
sslRequest[0] = 0x20; // length
sslRequest[3] = 0x01; // sequence number
sslRequest[4] = 0x05; // CLIENT_LONG_PASSWORD | CLIENT_LONG_FLAG
sslRequest[5] = 0xAA; // CLIENT_PROTOCOL_41 | CLIENT_SSL | CLIENT_TRANSACTIONS | CLIENT_SECURE_CONNECTION
sslRequest[6] = 0x28; // CLIENT_PLUGIN_AUTH | CLIENT_PLUGIN_AUTH_LENENC_CLIENT_DATA
sslRequest[10] = 0x80; // max packet size
sslRequest[12] = 33; // utf8
stream.Write(sslRequest, 0, sslRequest.Length);

// negotiate SSL
RemoteCertificateValidationCallback validate = (sender, cert, chain, errors) => true;
using var sslStream = new SslStream(stream, false, validate);
sslStream.AuthenticateAsClient("");

// display results
Console.WriteLine(sslStream.SslProtocol);
Console.WriteLine(sslStream.NegotiatedCipherSuite);
```

With .NET 5 on Windows, this displays:

```
Tls12
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
```

**Comment by kocburak** [comment] 2020-12-15 07:57
Thank you very much for the sample code. You are right. It gave the exact same error. It seems the problem is between google and apple some how...

**Comment by lauxjpn** [comment] 2020-12-15 11:15
That is weird. I have no issues connecting to a GCP MySQL 5.7 database using their generated `server-ca.pem`.

@kocburak Please try the code provided by @bgrainger against the following IP address: `35.192.154.86` (a GCP MySQL instance I created just for this issue).

I get the following result when run from Big Sur:

```
Tls12
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
```

What do you get?

**Comment by kocburak** [comment] 2020-12-15 11:42
It seems something changed between 31 May and last week (obviously Big Sur update). I can connect the DB of the IP you shared. Same as you:
Tls12
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256

My CA creation date was 31 MAY 2020 and should have valid until 29 MAY 2030. When I revoked all certificates and re create them error solved. As I stated previously, Google Cloud CA Certificate generation does not takes effect until the current CA revokes. Thank you for all of your help. Problem is neither about EF nor Connector. It is the Mac OS trusted CA list. And It should have listed on https://cloud.google.com/sql/docs/release-notes

**Comment by lauxjpn** [comment] 2020-12-15 12:03
@kocburak Well, the thing is that the CA certificates are usually self-signed and so is the `server-ca.pem` (at least the one my test instance uses). So it will never be of your operating systems certificate store anyway (unless of course you put it explicitly in there).
That is the reason, why you need to specify it explicitly, if you want to verify it, because the server certificate (that GCP does not allow you to download) has been signed by it.

If you still have the previously failing `server-ca.pem` at hand, run the following command against it:

```
openssl verify server-ca.pem
```

Compare that against the output when you run it again, but this time against the new `server-ca.pem` that works.
Maybe GCP did something weird to the old generated `server-ca.pem`.

**Comment by kocburak** [comment] 2020-12-15 12:20
There is not much of a difference between them.

`openssl verify server-ca_old.pem`
server-ca_old.pem: dnQualifier = d140a71d-6082-4d5d-9ef7-c933414b62b3, CN = Google Cloud SQL Server CA, O = "Google, Inc", C = US
error 18 at 0 depth lookup:self signed certificate
OK

`openssl verify server-ca.pem`
server-ca.pem: dnQualifier = 3f9d6b95-10cc-4147-97de-0545cc57d63e, CN = Google Cloud SQL Server CA, O = "Google, Inc", C = US
error 18 at 0 depth lookup:self signed certificate
OK

**Comment by lauxjpn** [comment] 2020-12-15 12:43
Was worth a shot. Then it might have to do with the server certificate instead of the ca/root certificate.
Anyway, thanks for looking into it.

**Comment by kocburak** [comment] 2020-12-15 12:54
No problem. If you have any more ideas i would like to check. And thank you for everyone who spend time into this. Besides, we still don't know the root cause and It is just weird.
