### ISSUE TITLE
Connections from pool do not appear to be reused with threaded async calls

### ISSUE THREAD

**Issue by TokenJedi** [mysql-net/MySqlConnector#859] opened 2020-07-24 20:15 UTC
### The issue
When calling the DB from async methods across multiple threads, I'm having an issue with the connection pool being exhausted even though DBContext has been disposed.

The code was initially using a `Parallel.For` and loading a `List<Task<List<someDto>>>` by calling an `async` method call without an await. That `async` method in turn makes multiple other `async` calls. I initially thought the `parallel.foreach` was causing a thread starvation issue and re-wrote the logic so that it was using a `SemaphoreSlim` to throttle the loop to 20 executions, yet I'm still having the issue.

The code is using a `SemaphoreSlim` to throttle a collection to 20 concurrent threads.
Each thread is loading a `List<Task<List<someDto>>>` and executing as such...
```
    var semaphore = new SemaphoreSlim(20);
    var tasks = new List<Task<List<someDto>>>();

    foreach (var widgets in groupedWidgetsByPortfolio)
    {
        await semaphore.WaitAsync(cancellationToken);
        tasks.Add(
            Task.Run(
                async () =>
                {
                    try
                    {
                        return await Validate(widgets.ToList(), request.UserInfo, widgets.Key, cancellationToken);
                    }
                    finally
                    {
                        semaphore.Release();
                    }
                },
                cancellationToken
            )
        );
    }

    var t = await Task.WhenAll(tasks);
    fileResults.Widgets = t.SelectMany(s => s).ToList();
```

The `Validate` call creates a "ValidationService" within an `IServiceScope` so that each "ValidationService" gets its own dependent "DataAccess" class resolved independently. The "ValidationService" makes many calls to the DB via the "DataAccess" class and each of those calls creates and disposes a new `DBContext` via a `using` statement.

`Validate` : 
```
    using (var scope = _serviceScopeFactory.CreateScope())
    {
        var validationService = scope.ServiceProvider.GetRequiredService<IValidationService>();

        _snipped for brevity_

        var validatedWidgets = await validationService.ValidateAsync(dataToValidate, cancellationToken);

        return validatedWidgets;
    }
```

`DataAccess` calls:
```
    using (var firmReadOnlyContext = _uow.FirmReadOnlyContext)
    {
        var simpleValidation = await firmReadOnlyContext.Foo
            .Where(x => x.Id== Id)
            .Select(x => new SimpleValidation
            {
                Baz = x.Baz,
                Fizz = x.Fizz
            })
            .FirstOrDefaultAsync(cancellationToken);

        return simpleValidation;
    }
```
OR
```
    var connection = _firmReadOnlyContext.Database.GetDbConnection();
    using (var command = connection.CreateCommand())
    {
        try
        {
            command.CommandType = CommandType.StoredProcedure;
            command.CommandText = "sprocName";
            command.Parameters.Add(new MySqlParameter("@InVar_Id", MySqlDbType.Int32) { Value = Id });
            command.Parameters.Add(new MySqlParameter("@InVar_AccountId", MySqlDbType.Int32) { Value = accountId });
            
            if (connection.State == ConnectionState.Closed)
                connection.Open();

            List<MyData> myData;

            using (var reader = await command.ExecuteReaderAsync(cancellationToken))
            {
                myData = reader.Translate<MyData>().ToList();
            }

            return myData;
        }
        finally
        {
            if (connection.State == ConnectionState.Open)
                connection.Close();
        }
    }
```

This has been added to our `DBContext.Dispose`
```
    public override void Dispose()
    {
        MySqlConnection.ClearAllPools();
        //MySqlConnection.ClearPool((MySqlConnection)Database.GetDbConnection());
        base.Dispose();
    }
```

To verify the number of connections that are getting created I've been monitoring our Aurora instance. 
When running threaded it takes about a minute to complete a batch. I'm not expecting the connection count to increase with each batch run since all of the connections from the previous batch should have been released to the pool. 
However, the below graphic shows the number of connections between each batch run continues to increase until we eventually get the error message below. 

What I also find interesting is that we get the error even though the connection string defines the MaxPool to 1000 
```
server={0};uid={1};pwd={2};database={3};TreatTinyAsBoolean=false;Convert Zero Datetime=True;MaxPoolSize=1000;MinPoolSize=0;ConnectionTimeout=120;
```

![image](https://user-images.githubusercontent.com/10510070/88005082-186b9980-cace-11ea-96af-ecb148e38768.png)

### Error Messages:
```
Message: Connect Timeout expired. All pooled connections are in use.

Stack Trace 1: 
MySql.Data.MySqlClient.MySqlException
  HResult=0x80004005
  Message=Connect Timeout expired. All pooled connections are in use.
  Source=MySqlConnector
  StackTrace:
   at MySql.Data.MySqlClient.MySqlConnection.<CreateSessionAsync>d__110.MoveNext() in /_/src/MySqlConnector/MySql.Data.MySqlClient/MySqlConnection.cs:line 670
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlConnection.<OpenAsync>d__26.MoveNext() in /_/src/MySqlConnector/MySql.Data.MySqlClient/MySqlConnection.cs:line 319
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlConnection.Open() in /_/src/MySqlConnector/MySql.Data.MySqlClient/MySqlConnection.cs:line 285
   at ....PreferenceRepository.<GetPreferencesValuesAsync>d__4.MoveNext() 

Inner Exception:
Message: OperationCanceledException: The operation was canceled.

StackTrace:
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Threading.SemaphoreSlim.<WaitUntilCountOrTimeoutAsync>d__33.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.SemaphoreSlim.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at MySqlConnector.Core.ConnectionPool.<GetSessionAsync>d__10.MoveNext() in /_/src/MySqlConnector/Core/ConnectionPool.cs:line 46
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlConnection.<CreateSessionAsync>d__110.MoveNext() in /_/src/MySqlConnector/MySql.Data.MySqlClient/MySqlConnection.cs:line 652

```

### Similar Issues reported to the SQLClient team
While researching this issue I came across the following post which is extremely similar. 
If you read through that you'll see at the end someone else reports having the issue with MySql and the SqlClient team punted it to the "MySql" team...which I'm hoping is you 😊

https://github.com/dotnet/SqlClient/issues/18

### Further technical details

MySQL version: 5.6.10
Operating system: connecting to MySql hosted in Aurora
Pomelo.EntityFrameworkCore.MySql version: 3.1.1
Microsoft.AspNetCore.App version: 3.1

Other details about my project setup:

**Comment by CatalinAdlerDF** [comment] 2020-07-25 10:17
Since updating to v1 I am also observing lots of connection pool issues, "session couldn't connect to server", "pool received invalid session, destroying it".

In addition, I've just noticed a warning from kestrel related to thread starvation; it might not be related, but as my app is full async (no .Wait() or .Result anywhere) I have to wonder if connection pool and thread starvation are somehow related.

Luckily for me, I can recover with a process recycle, but this is far from ideal.

I'm ASP .NET Core 3.1, GPP MySql 5.7, extensively using low-level ADP.NET + batch insert.

**Comment by bgrainger** [comment] 2020-07-26 22:13
> Since updating to v1

@CatalinAdlerDF which version did you update from?

**Comment by CatalinAdlerDF** [comment] 2020-07-27 14:52
0.69.6

**Comment by bgrainger** [comment] 2020-08-04 21:06
@TokenJedi I tried to reproduce this problem (using just the ADO.NET code, since I'm not very fluent in EFCore) but was unsuccessful. Are you able to narrow this down to a minimal, complete, reproducible example?

Alternatively, enabling DEBUG level logging and submitting the log files (you can email to <GitHub user name> @gmail.com) might provide some clues.

I don't know of any problems with (correctly) using separate database connections (with the same connection string, that are backed by the same pool) on different threads; the TechEmpower Framework Benchmarks do this without leaking connections (as an extreme example).

Ultimately, it looks like some kind of connection pool leak, but it's hard to know if there's a bug in MySqlConnector, a bug in Pomelo, or a failure to close/dispose a connection/context in your code.

**Comment by TokenJedi** [comment] 2020-08-07 23:48
@bgrainger Thank you for looking into this and for your reply.
I too suspect a connection leak somewhere (and likely on my side); however, we've tried everything to ensure a closed connection at the end of the connections use.

I'm not immediately sure if I'll be able to put together a reproducible example. I'll need to get a DB setup that I can use and share. We're currently using AWS Aurora and I'll need to check with my team if this would be possible
I'll also see if I can get the DEBUG logs turned on (I'll have to work with my team on that also) and hopefully that provides some insight.

Thank you again the suggestions.

**Comment by CatalinAdlerDF** [comment] 2020-08-08 08:54
Hi @bgrainger 

I think i got to the rca of my issues.
I had a db operation that got executed concurrently at high numbers (using ienumerable.select); I suspect this lead to exhausting the conn pool.

I've since switched to data flow to limit dop.
For the thread starvation i also think i have a rca; the `normal` dispose is blocking; switched to the async version.

I'll be monitoring and let you know how it goes.

**Comment by PhilAtWysdom** [comment] 2021-05-01 01:45
This was happening to us for a heavily used background service. I vaguely remembered reading something about HasRows being synchronous and in fact not the best way to check for rows in any case. Switching all those calls to .ReadAsync() resulted in this issue going away...

**Comment by bgrainger** [comment] 2021-11-28 01:47
Closing because I don't know if this is still an issue with v2.0 and I don't have a consistent repro.

**Closed by bgrainger** 2021-11-28 01:47 UTC
