### ISSUE TITLE
A different type returned fomr DataReader after calling Prepare()

### ISSUE THREAD

**Issue by kliszaq** [mysql-net/MySqlConnector#1403] opened 2023-11-29 09:11 UTC
**Software versions**
MySqlConnector version: 2.3.1
Server type (MySQL, MariaDB, Aurora, etc.) and version: MySql 5.7.33
.NET version: .NET8

**Describe the bug**
When calling the COALESCE function for varchar and decimal the returned value is a string. When using Prepare() the GetString() method on the reader throws ""System.InvalidCastException: 'Unable to cast object of type 'System.Byte[]' to type 'System.String'.'. 

**Exception**
N/A

**Code sample**

```csharp
string connectionString = "Server=localhost;Port=3306;User ID=qt52052821415;Password=pass;Database=db;Pooling=False;Allow Zero DateTime=True;Auto Enlist=False;Character Set=utf8;Convert Zero DateTime=True;SSL Mode = None;";
using var connection = new MySqlConnection(connectionString);
connection.Open();
using var command = new MySqlCommand("SELECT COALESCE(@a, @b) AS `result` FROM dual", connection);
command.CommandTimeout = 0;
 
// Uncomment prepare to see the difference!
// command.Prepare();

DbParameter param1 = command.CreateParameter();
param1.ParameterName = "a";
param1.Size = 15;
param1.Precision = 0;
param1.Scale = 0;
param1.IsNullable = true;
param1.DbType = DbType.String;
param1.Value = "2.5";
 
DbParameter param2 = command.CreateParameter();
param2.ParameterName = "b";
param2.Size = 0;
param2.Precision = 12;
param2.Scale = 6;
param2.IsNullable = true;
param2.DbType = DbType.Decimal;
 
command.Parameters.Add(param1);
command.Parameters.Add(param2);
 
MySqlDataReader dataReader = command.ExecuteReader(CommandBehavior.SequentialAccess);
dataReader.Read();
string value = dataReader.GetString(0);
// without Prepare() the returned result is "2.5"
```

**Expected behavior**
I would expect that types returned before and after Prepare() are the same - in this case it is a string.

**Additional context**
N/A

**Comment by bgrainger** [comment] 2023-11-29 14:16
Thanks for the detailed bug report!

This doesn't repro with `mysql:8.0.35`, so it seems plausible that it's a MySQL Server bug. (If the server is reporting that the returned data is `VARBINARY` then MySqlConnector will not automatically convert it to a `string` if `GetString` is called; this is by design.)

I can investigate further to see if MySqlConnector is not interpreting the returned data correctly (but my suspicion is that it is). As a workaround, you can perform a type test and convert it yourself:

```csharp
string value = dataReader.GetValue(0) switch
{
	string s => s,
	byte[] b => Encoding.ASCII.GetString(b),
	_ => throw new NotSupportedException(),
};
```

**Comment by bgrainger** [comment] 2023-11-29 14:24
Executing the prepared statement in MySQL Workbench returns a "BLOB":

![prepared statement output](https://github.com/mysql-net/MySqlConnector/assets/188129/13ad39d1-08fb-4f62-b0c1-0f86b46b0e3b)

The returned field type is `VARBINARY`. MySqlConnector is correctly reporting the data returned from the server. (You could file a bug report at bugs.mysql.com but since 5.7 is EOL and it's already fixed in 8.x, it's probably not worth it.)

**Closed by bgrainger** 2023-11-29 14:24 UTC
Labels: invalid

**Comment by kliszaq** [comment] 2023-11-29 14:31
Thanks for your replies!
Now everything is clear. Please close the bug.
