### ISSUE TITLE
m_session might be null and probably causing crash of the application

### ISSUE THREAD

**Issue by lukashovancik** [mysql-net/MySqlConnector#1178] opened 2022-05-31 13:54 UTC
![Screenshot 2022-05-31 at 15 49 50](https://user-images.githubusercontent.com/11795945/171189486-3e924c99-5de2-4c1c-9225-44a934572fc4.png)

_Some information about our application:_

Package version **- 2.1.7**
Dotnet version - **.net6**
Platform - **debian 11**

We can see this error from time to time in the application. We also noticed that it might be correlating with database maintenance. 

Could you check it out please ? 

Thank you.

**Comment by bgrainger** [comment] 2022-05-31 16:02
Duplicate of #1177

**Closed by bgrainger** 2022-05-31 16:02 UTC
