### ISSUE TITLE
Add MySqlErrorCode.InvalidJsonText

### ISSUE THREAD

**Issue by marco6** [mysql-net/MySqlConnector#1182] opened 2022-06-14 12:34 UTC
**Is your feature request related to a problem? Please describe.**
We found that there is at least one error code not present in the enum MySqlErrorCode (3140, invalid json). It could be nice to check if others are missing.

**Describe the solution you'd like**
Adding MySqlErrorCode.InvalidJson = 3140 to the enum

**Describe alternatives you've considered**
Right now we are casting to `int` like `catch (MySqlExceptione) when((int)e.ErrorCode == 3140)`

**Comment by bgrainger** [comment] 2022-06-15 15:24
That enum value already exists: https://github.com/mysql-net/MySqlConnector/blob/917b7764b2287abe5d2d962a52bf4a736659cb68/src/MySqlConnector/MySqlErrorCode.g.cs#L3318-L3321

Duplicate of https://github.com/mysql-net/MySqlConnector/issues/1048

**Comment by bgrainger** [comment] 2022-06-15 15:24
Duplicate of https://github.com/mysql-net/MySqlConnector/issues/1048

**Closed by bgrainger** 2022-06-15 15:24 UTC

**Comment by marco6** [comment] 2022-06-15 15:26
Thank you! I was looking for an issue while I should have looked in the code first. 

Sorry for de duplicate issue! :-)
