### ISSUE TITLE
Connecting is stuck in the server even though connect timeout reaches

### ISSUE THREAD

**Issue by firephantomassasin** [mysql-net/MySqlConnector#941] opened 2021-02-10 02:33 UTC
Connecting / connection is stuck in the DB server even though connect timeout reaches already in the app / code side

using version 0.65 both async and sync is experiencing this kind of error. Leaving the connection connecting in the DB server creates a negative domino effect and was able to reach the max connections right away.

Any suggestions or recommendations on how to resolve this? Is upgrading to the latest version (1.2.1) will fix this kind of issue?

**Comment by bgrainger** [comment] 2021-02-11 20:42
I'm not sure what this means. It sounds like you're expecting an exception after `ConnectTimeout` seconds, but that's not happening?

Do you have a repro?

If it happens for sync open, do you have a callstack showing what the code is doing when this happens?

**Comment by firephantomassasin** [comment] 2021-02-12 14:23
Hello, we are using async for open, (Full async open, query, closing and disposing). We are receiving exception after the connect timeout seconds but upon checking on the DB Server, the connection still tries to connect to the DB server (just like the screenshot below) it doesn't get cancelled as well if timeout exception occurred on the app / code side already. 

I am not sure if what we're experiencing is related to this issue: Fix connection pool leak when a failure (e.g., timeout) occurs on a connection: #836 https://github.com/mysql-net/MySqlConnector/issues/836.



![image](https://user-images.githubusercontent.com/8090574/107779601-8e906000-6d80-11eb-8f18-e6620ff7bcc0.png)


We tried updating to the latest version 1.2.1, and we will observe in this coming weeks.

**Comment by bgrainger** [comment] 2021-02-12 14:42
It seems very odd that the User, Host, DB, and State are all `None` in that screenshot.

This possibly seems like a server bug. If the client has disconnected, the server should free up the resources it no longer needs. What DB Server and version are you using?

**Comment by firephantomassasin** [comment] 2021-02-12 14:45
We are using  MySQL 5.7.17-log

**Comment by bgrainger** [comment] 2021-02-12 15:24
Can you "Show Details" for some of those "None" server threads and examine the connection attributes?

**Comment by firephantomassasin** [comment] 2021-02-13 12:44
We will try to check the details if it happens again. We will observe on Monday since this only happens during peak hours of our platform.

**Comment by bgrainger** [comment] 2021-03-01 17:00
Is this a possible duplicate of https://github.com/mysql-net/MySqlConnector/issues/947?

Make sure to `Dispose` _every_ `MySqlConnection` object that is created.

**Comment by firephantomassasin** [comment] 2021-03-02 01:40
Hi! So far we haven't encountered this kind of issue again after updating the library to 1.2.1. We'll update here once again if ever we experienced this kind of issue again. Thank you for your help.

**Comment by bgrainger** [comment] 2021-03-02 05:08
Closing this for now, as we don't have a repro. Feel free to reopen if it becomes a problem again.

**Closed** 2021-03-02 05:08 UTC
