### ISSUE TITLE
[Note] Bad handshake

### ISSUE THREAD

**Issue by paulb2015** [mysql-net/MySqlConnector#726] opened 2019-10-21 12:03 UTC
The MySQL Server error log is logging "[Note] Bad handshake" whenever a connection is made from a client using this connector.

If I change the connector to the MySql.Data library, I no longer get this error.

Connections are being made from Windows Server 2019 to a MySQL 5.7 on Ubuntu 18.04.3 LTS.

MySQL Server = 5.7.27
MySqlConnector = 0.60.1
MySql.Data = 6.9.12

The error goes away if I set ssl = 0 in the MySQL Server configuration file.

**Comment by bgrainger** [comment] 2019-10-23 16:08
This is caused by MySqlConnector attempting to negotiate TLS 1.2 or 1.3 during the TLS handshake. MySQL 5.7.26 (built with yaSSL as its SSL library) only supports TLS 1.1.

I don't know why yaSSL is logging `Bad handshake`, but it's a spurious warning. MySQL Server 5.7.27 replaces yaSSL with OpenSSL; if you upgrade to 5.7.27, the warning will go away, and your connection will be secured with TLS 1.2 automatically.

(Note that MySql.Data will still negotiate TLS 1.1 with MySQL Server 5.7.27; I'm not sure if that's a hardcoded maximum version, or if there is some other limitation in MySql.Data.)

The point of TLS negotiation is to automatically select the best protocol that both client and server can support, so I don't plan to work around this by doing MySQL version sniffing or similar; that would be error-prone and could result in bad side-effects such as not automatically using TLS 1.2 when an upgraded MySQL Server comes out.

**Comment by paulb2015** [comment] 2019-10-23 16:25
Thanks for the response.

I am already using 5.7.27 as originally stated.

The main issue, for me, that this problem causes is filling up the error log, which makes it difficult to diagnose other problems, and can also lead to the hard disk filling up a lot more quickly.

```
mysql> select version();

+------------+
| version()  |
+------------+
| 5.7.27-log |
+------------+
```

**Comment by bgrainger** [comment] 2019-10-23 17:31
Sorry, I somehow misread your original issue as 5.7.26.

I'm not able to reproduce with the `mysql:5.7.27` Docker image (though I can with `mysql:5.7.26`, which is why I assumed this was a yaSSL/OpenSSL issue).

Does your client still negotiate TLS even though bad handshake is logged? You can check with:

```csharp
using (var cmd = new MySqlCommand("show status like 'Ssl_version';", connection))
using (var reader = cmd.ExecuteReader())
{
	reader.Read();
	var sslVersion = reader.GetString(1); // should be "TLSv1.2"
}
```

**Comment by bgrainger** [comment] 2019-10-23 17:35
I really confused myself and mixed up my version numbers. The change (to OpenSSL) is in MySQL 5.7.28: https://dev.mysql.com/doc/relnotes/mysql/5.7/en/news-5-7-28.html

So: upgrading to 5.7.28 should solve this problem for you; I'll edit my previous post.

**Comment by bgrainger** [comment] 2019-10-23 17:41
Note also that MySql.Data 6.9.12 doesn't log an error because it's hard-coded to support a maximum of TLS 1.1; if you used MySql.Data 8.0.18, it also would cause the server to log `[Note] Bad handshake`.

**Comment by bgrainger** [comment] 2019-10-23 17:43
The MySqlConnector behaviour is exactly the same as the latest version of MySql.Data against MySQL Server 5.7.27.

This is a server-side problem where a non-error is logged unnecessarily during TLS negotiation. It can be fixed by updating to the latest version of MySQL Server (5.7.28 or later, or 8.x).

**Closed by bgrainger** 2019-10-23 17:43 UTC
