### ISSUE TITLE
ConnectionString does not support multi server with different port

### ISSUE THREAD

**Issue by naughtyGitCat** [mysql-net/MySqlConnector#1159] opened 2022-04-08 02:07 UTC
**Software versions**
MySqlConnector version:
Server type (MySQL, MariaDB, Aurora, etc.) and version: MySQL5.7
.NET version: 5.0
(Optional) ORM NuGet packages and versions: NPOCO latest

**Describe the bug**

ConnectionString does not support multi-server with different port

**Exception**
Full exception message and call stack (if applicable)

**Code sample**

```csharp
/* A concise code sample to reproduce the bug */
        public MySqlConnection GetReadOnlyConnection()
        {
            _logger.LogDebug("Now get a readonly connection");
            return new MySqlConnection(_mysqlConfig.ReadOnlyURI);
        }
```
```json
    "MySQL": {
        "ReadWriteURI": "server=A;port=3306;user=****;password=****;database=***",
        "ReadOnlyURI": "server=B:3307,A:3306;user=***;password=***;database=***;LoadBalance=FailOver"
    },
```

**Expected behavior**
'B:3307,A:3306' works

**Comment by bgrainger** [comment] 2022-04-08 02:37
MySqlConnector doesn't currently support this Connector/NET connection string format of specifying a different port for each server.

**Comment by bgrainger** [comment] 2022-04-08 02:37
Duplicate of #762

**Closed by bgrainger** 2022-04-08 02:37 UTC
