### ISSUE TITLE
Increase minimum .NET target to NET462?

### ISSUE THREAD

**Issue by iamcarbon** [mysql-net/MySqlConnector#1205] opened 2022-08-18 23:23 UTC
Is there any reason to keep the net452 target around? 

.NET 4.6.1 has also gone out of support. We should consider raising he minimum framework target to .NET4.6.2.

This would help simplify the codebase and reduce the development dependencies needed to contribute to the project.

**Comment by bgrainger** [comment] 2022-08-19 00:20
Duplicate of https://github.com/mysql-net/MySqlConnector/issues/636

**Closed by bgrainger** 2022-08-19 00:20 UTC
