### ISSUE TITLE
Async null reference exceptions

### ISSUE THREAD

**Issue by TrellyTB** [mysql-net/MySqlConnector#851] opened 2020-07-16 19:26 UTC
Hello,
Just downloaded MySqlConnector and was trying it in a simple test environment. 
Some of the Async commands work, others generate System.NullReferenceException: 'Object reference not set to an instance of an object.'
When I replace the problem async call with non-async it runs fine.
I just can't see the problem in my code, and have tried many variations, so thought I would ask here.

Environment: C# in Visual Studio 2019, .net Core 3.1, pulling from a remote MySql test table.

```cs
        private void TestMySqlAsync()
        {
            using (MySqlConnection AppDb = new MySqlConnection("Server=blah blah"))
            {
                Task.Run(() => AppDb.OpenAsync())
                    .ContinueWith(task => TestReader(AppDb))
                    .Wait();
            }
        }

        public async Task TestReader(MySqlConnection AppDb)
        {
            try
            {
                using (var cmd = AppDb.CreateCommand())
                {
                    cmd.CommandText = @"SELECT `ID`, `Name`, `Address`, `City`, `State` FROM `ScrapMetal`;";
                    //using (MySqlDataReader reader = cmd.ExecuteReader())   // This works with no issue
                    using (MySqlDataReader reader = await cmd.ExecuteReaderAsync()) // System.NullReferenceException: 'Object reference not set to an instance of an object.'
                    {
                        while (await reader.ReadAsync())  // This also works
                        {
                            Debug.WriteLine("<{0}>  <{1}>  <{2}>  <{3}>  <{4}>",
                                reader.GetInt32("ID").ToString(),
                                reader.GetString("Name"),
                                reader.GetString("Address"),
                                reader.GetString("City"),
                                reader.GetString("State"));
                        }
                    }
                }
            }
            catch(Exception ex)
            {
                Debug.WriteLine(ex.Message);
            }
        }
```

Thanks for any help, I would really like to get the async code running.

**Comment by bgrainger** [comment] 2020-07-16 19:44
What's the full exception call stack?

There are plenty of tests in the code for `ExecuteReaderAsync`, so throwing a `NullReferenceException` is unexpected. E.g., https://github.com/mysql-net/MySqlConnector/blob/bb39cd80690ff172c28c6440aa73c320b752733a/tests/SideBySide/QueryTests.cs#L1179-L1183

Is it possible your main thread is closing the connection while it's still in use by `TestReader`? `ContinueWith` and `Wait` are kind of "anti patterns" in modern async C# code.

**Comment by bgrainger** [comment] 2020-07-16 20:07
I'm not able to reproduce a `NullReferenceException` using the code you provided (but using a different table).

What's your remote MySQL Server brand and version?

**Comment by TrellyTB** [comment] 2020-07-16 21:20
Sorry, just went on lunch break.

This exception was originally thrown at this call stack:
    [External Code]
    WPFC_TestApp.MainWindow.TestReader(MySqlConnector.MySqlConnection) in MainWindow.xaml.cs

From the Exception Stack trace:

   at MySqlConnector.MySqlDataReader.ActivateResultSet() in /_/src/MySqlConnector/MySqlDataReader.cs:line 115
   at MySqlConnector.MySqlDataReader.<CreateAsync>d__97.MoveNext() in /_/src/MySqlConnector/MySqlDataReader.cs:line 421
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySqlConnector.Core.CommandExecutor.<ExecuteReaderAsync>d__0.MoveNext() in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 61
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at WPFC_TestApp.MainWindow.<TestReader>d__4.MoveNext() in C:\Users\mhama\Documents\Visual Studio 2019\Projects\WPFC_TestApp\WPFC_TestApp\MainWindow.xaml.cs:line 77

Not sure if this is what you are looking for.
Thanks for the speedy response, I thought I had time to head out :)

**Comment by TrellyTB** [comment] 2020-07-16 21:25
I set up this test database at ICDsoft, this is the info on what they run:

    Server: Localhost via UNIX socket
    Server type: MySQL
    Server connection: SSL is not being used Documentation
    Server version: 5.7.29-percona-sure1-log - MySQL Community Server (GPL)
    Protocol version: 10
    User:
    Server charset: cp1252 West European (latin1)

**Comment by TrellyTB** [comment] 2020-07-16 21:28
I can send the connection string to you to try out, it is just a test database. Where should I send it?

**Comment by TrellyTB** [comment] 2020-07-16 22:02
Ok, I restructured it to take out the ContinueWith and Wait statements, and now it works just fine. Sorry == it's really hard to figure out what is the newest way of implementing things, and I thought that was the way to go.

**Comment by bgrainger** [comment] 2020-07-16 22:26
The line of the crash is https://github.com/mysql-net/MySqlConnector/blob/30856673fad278cfa543079ecce0c28d5a370e49/src/MySqlConnector/MySqlDataReader.cs#L115

It seems like `m_resultSet` is `null`.

That's being called from https://github.com/mysql-net/MySqlConnector/blob/30856673fad278cfa543079ecce0c28d5a370e49/src/MySqlConnector/MySqlDataReader.cs#L420-L421

It's clear that `m_resultSet` must not have been `null` there.

It's only set to `null` here in `Dispose`: https://github.com/mysql-net/MySqlConnector/blob/30856673fad278cfa543079ecce0c28d5a370e49/src/MySqlConnector/MySqlDataReader.cs#L568

This sounds like a race condition where one of your threads is calling `Dispose` on the `MySqlDataReader` while it's still in use. Some misuses like that will be caught (and throw an `ObjectDisposedException`) but in general it corrupts internal state and can crash unpredictably.

Removing `ContinueWith` sounds good to me.

**Closed by bgrainger** 2020-07-16 22:26 UTC
