### ISSUE TITLE
Implement CommandBehavior.SchemaOnly

### ISSUE THREAD

**Issue by jacentino** [mysql-net/MySqlConnector#1281] opened 2023-01-30 22:12 UTC
SchemaOnly command execution mode would be useful in some runtime code generation scenarios. It allows to discover query result structure without real execution. 
I used this mode to implement microORM for F#. Thanks to SchemaOnly-based code generation data access code is almost as maintainable as it was statically typed, even if queries are simple strings.

**Comment by bgrainger** [comment] 2023-01-31 14:33
This was implemented in https://github.com/mysql-net/MySqlConnector/issues/723.

Is there something wrong with the current implementation?

**Comment by bgrainger** [comment] 2023-01-31 14:33
Duplicate of #723

**Closed by bgrainger** 2023-01-31 14:33 UTC

**Comment by jacentino** [comment] 2023-01-31 20:44
When I executed following command in SchemaOnly mode:

insert into blog (name, title, description, owner, createdAt, modifiedAt,
modifiedBy)
values ***@***.***, @title, @description, @owner, @createdAt, @modifiedAt,
@modifiedBy);
select last_insert_id()

The insert part was executed and a new record was added.
That's why I thought it was not implemented at all.

Actually, the current implementation is enough for me.

wt., 31 sty 2023 o 15:33 Bradley Grainger ***@***.***>
napisał(a):

**Comment by bgrainger** [comment] 2023-01-31 23:17
I think `CommandBehavior.SchemaOnly` is only well-defined for a `SELECT` query, i.e., something that returns a result set. Using it with other DML or DDL commands is not well-defined.

**Comment by jacentino** [comment] 2023-02-01 21:43
Indeed.
System.Data..SqlClient doesn't execute command even if it has no result, e.g.:

insert into blog (name, title, description, owner, createdAt, modifiedAt, modifiedBy) 
values ( @name, @title, @description, @owner, @createdAt, @modifiedAt, @modifiedBy)

The same query is executed by NpgSql, OracleClient and MySql.Data and a new row is created.
But if we add select returning id, none of them produces side effects.
