### ISSUE TITLE
Memory leak bug

### ISSUE THREAD

**Issue by UnoSD** [mysql-net/MySqlConnector#49] opened 2016-09-09 12:13 UTC
The following code causes a memory leak on Linux:

```
using (var connection = new MySqlConnection(_connectionString))
{
    await connection.OpenAsync();

    using (var transaction = connection.BeginTransaction())
    using (var command = new MySqlCommand(connection, transaction))
    {
        command.CommandText = "SOMESQL";
        command.ExecuteNonQuery();

        command.CommandText = "SOME OTHER SQL";
        command.ExecuteScalar();

        transaction.Commit();
    }
}
```

I couldn't investigate it further, but **lldb** with the **SOS plugin** shows **System.String** containing the queries accumulating in the heap.

Please let me know if you would like some more details.

**Comment by caleblloyd** [comment] 2016-10-04 21:07
@UnoSD  there have been a lot of changes since you opened this that may have fixed your issue.  Could you try re-testing with the [latest version](https://www.nuget.org/packages/MySqlConnector/)?

I'm not using any advanced profiling tools, but here's what I see in `top` on Ubuntu 16.04 when I run 900,000 requests through the [Performance Test](https://github.com/bgrainger/MySqlConnector/tree/master/tests/MySqlConnector.Performance):

    Before test: 0.4% system memory usage (Approx 64MB on my machine)
    During test: 1.1% peak, 0.8% average system memory usage
    After test:  0.6% system memory usage

It looks like Garbage Collection is doing a pretty good job.  I wouldn't expect the memory percentages to match before/after exactly because .NET does not have to release all of it's free memory back to the OS.

The only difference after running requests through the library should be that if connection pooling is on, there will be up to `mas pool size` (default=100) Open Connections and their associated memory footprint.

The performance test runs a mix of `INSERT` and `SELECT` statements.  The specific performance test command that I used was `./stress.sh 1500 600s async`

**Comment by UnoSD** [comment] 2016-10-18 10:24
@caleblloyd When I get a chance I will update to the latest version and give you feedback on the results.

Any chance the problem is with the transaction code? Is the performance test tool validating this scenario?

Thank you.

**Comment by bgrainger** [comment] 2017-03-24 06:09
Not able to repro, and no feedback in the last five months; closing.

**Comment by UnoSD** [comment] 2017-03-24 22:58
Haven't had a chance to look at it any more, but I tried updating to the new version and it still leaks. I will try and switch to MySQL.Data (not sure got the name right) and see if the problem goes away or not.

**Comment by UnoSD** [comment] 2017-03-25 16:43
@bgrainger apologies if it takes so long, but I have been able to reproduce the leak only in production with some big load. We restart the service as a workaround when the memory usage get too high, so resolving the issue has low priority and I might not be able to look at it for a while. Happy to close this for now and when I get a chance to do the test I'll give some feedback.

**Comment by bgrainger** [comment] 2017-03-27 00:23
@UnoSD Can you post your connection string (without the password)?

**Comment by UnoSD** [comment] 2017-03-27 09:05
@bgrainger of course: `Server=<SERVER>;Database=<DB>;Uid=<User>;Pwd=<PASSWORD>`

I can't share the other details, but the server is `xxxxx.amazonaws.com` user is characters and underscore and a number and db is just four characters.

**Comment by UnoSD** [comment] 2017-03-27 09:16
![capture](https://cloud.githubusercontent.com/assets/1582987/24349250/4d3e0a48-12d6-11e7-895a-7f9d189c6e25.PNG)

This is what our service currently does. Leaks memory until it gets killed by the OOM (is running on Linux) and then starts all over again.

**Comment by UnoSD** [comment] 2017-06-20 13:14
I managed to take a memory dump of the process and analyse it, unfortunately I can't find any managed memory leak; it's likely to be unmanaged, it may very well be a coreclr bug, I will investigate more and let you know if I find anything.

Any idea about suspicious unmanaged memory allocation in the codebase?

**Comment by bgrainger** [comment] 2017-06-20 13:39
> Any idea about suspicious unmanaged memory allocation in the codebase?

All unmanaged memory usage that I can think of would be wrapped by some .NET object, e.g., `Socket`, `SslStream`. Those objects are kept alive if the connection is pooled, but should be shut down when the connection is removed from the pool.

However, now that I look at the code, I see some objects (e.g., `SslStream`) that aren't being disposed correctly and could result in (short-term) leaks. I would still expect the .NET Finalizer to clean up the unmanaged resources associated with these objects (after a short period of time) so there shouldn't be unbounded memory growth even if MySqlConnector isn't disposing all its objects correctly.

**Comment by bgrainger** [comment] 2017-06-20 13:42
Is it possible that .NET Core on Linux doesn't GC aggressively if there is lots of free memory on the system? For instance, many of the objects may be dead, but not getting collected because the system has >70% free memory.

To test this theory, you could write a "watchdog thread" that wakes up once per minute and runs

```
GC.Collect();
GC.WaitForPendingFinalizers();
GC.Collect();
```

This is a nasty workaround, but I think would be an interesting experiment to see if the memory usage pattern of your application changes.

**Comment by UnoSD** [comment] 2017-06-20 14:05
@bgrainger it's quite a tiny VM, indeed the process gets often killed as it uses almost all the memory available on the machine. I can try and replace MySqlConnector with MySql.Data to see if we get the same issue so we can be 100% sure and know if it's the library or the CLR. I hope the API is not that different.

**Comment by bgrainger** [comment] 2017-06-20 14:20
I opened #275 to track SslStream not being disposed.

**Comment by bgrainger** [comment] 2017-06-21 00:12
I shipped a fix for disposing `SslStream` in [0.20.2](https://www.nuget.org/packages/MySqlConnector/0.20.2); can you re-test with that and see if it still exhibits the native memory problem?

**Comment by UnoSD** [comment] 2017-06-21 10:05
Sure, is it in NuGet already?

**Comment by UnoSD** [comment] 2017-06-22 09:22
Unfortunately that didn't help, memory grew from 3% to 17% of the machine overnight. I need to test with the MySQL.Data (which is in prerelease for Core so I'm not ever really happy adding it).

**Comment by bgrainger** [comment] 2017-06-23 15:20
@UnoSD Is the code snippet in your original bug report still sufficient to reproduce the problem?

**Comment by UnoSD** [comment] 2017-06-29 08:20
@bgrainger cannot be entirely sure until I rule out the framework I can reproduce it only in production

**Comment by bgrainger** [comment] 2018-01-02 06:42
Will reopen if there's more evidence that the leak is from MySqlConnector.

**Closed by bgrainger** 2018-01-02 06:42 UTC
Labels: can't reproduce

**Comment by UnoSD** [comment] 2018-01-04 08:53
Apologise if I wasn't able to cut some time to test, I will send some updates if we get back to it.
