### ISSUE TITLE
Issue with MaxScale 6.2 Load Balancer

### ISSUE THREAD

**Issue by ertaboy356b** [mysql-net/MySqlConnector#1234] opened 2022-10-27 06:03 UTC
**Software versions**
MySqlConnector version: 2.1.13, 2.2.0-rc1
Server type (MySQL, MariaDB, Aurora, etc.) and version: MariaDB, MaxScale
.NET version: 4.7.2
*Using Dapper

**Describe the bug**
Calling an Open or OpenAsync after the other one closes seems to block the entire application, halting the entire application.
Tried another method with a transaction and several ExecuteAsync methods and the code always blocks on the next ExecuteAsync.

No Issues with an older version of MaxScale (2.5). No Issues with direct connection to a database node.

Pooling=False seems to fix this issue at first but causes block in some way or another.

**Exception**
No exception, it just blocks resulting to a Timeout after sometime.

**Code sample**

```csharp
        public async Task Method1Async()
        {
            using (var domain = new MySqlConnection())
            {
                await domain.OpenDBAsync(); // Extension method with connectionstring

                await domain.QueryAsync(@"SELECT * FROM table LIMIT 1");
            }
        }

        public async Task Method2Async()
        {
            using (var domain = new MySqlConnection())
            {
                await domain.OpenDBAsync(); // Code blocks here after running Method1Async()

                using (var trans = await domain.BeginTransactionAsync())
                {
                    await domain.ExecuteAsync("UPDATE .....");

                    await trans.CommitOrRollbackAsync(); // Extension method for commit or rollback
                }
            }
        }

        public async Task MethodToRunAsync()
        {
            await Method1Async();
            await Method2Async(); // Blocks Here
        }

        // Extension
        public static async Task OpenDBAsync(this MySqlConnection conn, bool allowUserVariables = false)
        {
            if (_connectionString == null)
            {
                var user = ConfigReader.Get("USER").Decrypt();
                var pass = ConfigReader.Get("PASSWORD").Decrypt();
                var dbName = ConfigReader.Get("DATABASE_NAME").Decrypt();
                var ipAddress = ConfigReader.Get("IP_ADDRESS");
                var port = ConfigReader.Get("PORT");

                _connectionString = $"Server={ipAddress};Port={port};Database={dbName};Uid={user};Pwd={pass};Pooling=True;IgnoreCommandTransaction=True;";
            }

            conn.ConnectionString = _connectionString;

            if (allowUserVariables)
            {
                conn.ConnectionString += ";Allow User Variables = True";
            }

            await conn.OpenAsync();
        }
```

**Expected behavior**
Program should not block as expected.

**Additional context**
If you reverse Method1Async() and Method2Async(), Method1Async will be blocked instead on OpenDBAsync()

**Comment by bgrainger** [comment] 2022-10-28 23:23
I tried to reproduce this with the following sample: https://gist.github.com/bgrainger/7cc049f163d64f4b71d6e666fd30a954

There's a Docker Compose file that spins up mariadb:10.8 behind maxscale:2.5

The C# program connects to the MaxScale service and executes simple queries.

When I change it to use `maxscale:6.4`, everything still works as expected.

Can you provide a full self-contained repro that demonstrates the hang?

**Comment by ertaboy356b** [comment] 2022-10-29 03:20
The database admin tested with 6.4 and 7 and both works as expected. 

The repro is mostly correct except for the Max Scale version number which is 6.2.0.

I asked the admin but refuses to provide configuration. 
All I know is that it's a MariaDB cluster with single write node and multiple read nodes.

I can make a code and video about it if that helps.

https://youtu.be/ylwdMklxoZ8

``` Csharp
using Dapper;
using MySqlConnector;

await MethodToRunAsync();

async Task GetDataToImportAsync(int importId)
{
    using (var domain = new MySqlConnection())
    {
        await domain.OpenOldDBAsync();
        await domain.QueryAsync(@"SELECT 1");
    }
}


async Task<int> GetLastImportIdAsync()
{
    using (var domain = new MySqlConnection())
    {
        await domain.OpenNewDBAsync();
        var importId = await domain.QueryFirstOrDefaultAsync<int>("SELECT 1");

        return importId;
    }
}

async Task ImportTasksAsync()
{
    using (var domain = new MySqlConnection())
    {
        await domain.OpenNewDBAsync();

        using (var trans = await domain.BeginTransactionAsync())
        {
            await domain.ExecuteAsync("SELECT 1; ");

            await trans.RollbackAsync();
        }
    }
}

async Task MethodToRunAsync()
{
    while (true)
    {
        try
        {
            var importId = await GetLastImportIdAsync();
            await GetDataToImportAsync(importId);
            await ImportTasksAsync(); // Blocks Here
        }
        catch (Exception ex)
        {
            throw;
        }
    }
}

public static class ExtensionMethods
{
    #region Sensitive Stuff
    const string OLD_DB = "";
    const string NEW_DB = "";
    const string USER = "";
    const string PASS = "";
    const string LB_IP = "";
    const string LB_PORT = "";
    #endregion

    public static async Task OpenOldDBAsync(this MySqlConnection conn, bool allowUserVariables = false)
    {
        conn.ConnectionString = $"server={LB_IP};port={LB_PORT};database={OLD_DB};user={USER};password={PASS}";
        await conn.OpenAsync();
    }

    public static async Task OpenNewDBAsync(this MySqlConnection conn, bool allowUserVariables = false)
    {
        conn.ConnectionString = $"server={LB_IP};port={LB_PORT};database={NEW_DB};user={USER};password={PASS}";
        await conn.OpenAsync();
    }
}
```

**Comment by bgrainger** [comment] 2022-10-29 04:28
I just tried with `mariadb/maxscale:6.2.3` and still no problem. (Don't know how I missed the version number the first time around.) Unfortunately there doesn't appear to be a Docker image for 6.2 earlier than that.

MySqlConnector should never completely hang; if the server is non-responsive it should throw a `MySqlException` for a connection timeout. I assume that you have waited more than the default 15 seconds. Does adding `;ConnectionTimeout=3` to your connection string cause any exception at three seconds, or does it still hang?

Can you turn on verbose logging by putting the following line of code at the beginning of your program, then uploading the logs here (or emailing them to me directly)?

```csharp
MySqlConnector.Logging.MySqlConnectorLogManager.Provider = new MySqlConnector.Logging.ConsoleLoggerProvider(MySqlConnector.Logging.MySqlConnectorLogLevel.Trace, true);
```

**Comment by bgrainger** [comment] 2022-10-29 04:31
If you are using 6.2.0, there's a potentially-relevant bug that was [fixed in 6.2.2](https://mariadb.com/docs/release-notes/mariadb-maxscale-6/6-2-2/):

> * Slow reverse DNS lookups during authentication can cause MaxScale to stall.

I don't know if that might possibly be a problem in your environment? (But even if MaxScale does stall, MySqlConnector should still time out.)

**Comment by bgrainger** [comment] 2022-10-29 04:46
I built a Docker image for `maxscale:6.2.0` by starting with https://github.com/mariadb-corporation/maxscale-docker/tree/13205f02b13462edeafc0a099f9e201088aed0e2 then setting `MXS_VERSION=6.2.0`.

I see a small delay (when running my program) between these two log lines:

```
[TRACE] ServerSession   Session1.1 creating connection attributes
[TRACE] ConnectionPool  Pool1 returning new Session1.1 to caller; LeasedSessionsCount=1
```

However, the program then continues and runs to completion successfully.

**Comment by ertaboy356b** [comment] 2022-10-29 05:28
Here's the log. I have added ConnectionTimeout=3 to the connectionstring but the program did not throw an error.

```
[INFO]  ConnectionPool  Pool1 creating new connection pool for ConnectionString: <REDACTED>;Connection Timeout=3
[TRACE] ConnectionPool  Pool1 waiting for an available session
[TRACE] ServerSession   Session1.1 created new session
[DEBUG] ConnectionPool  Pool1 no pooled session available; created new Session1.1
[TRACE] ServerSession   Session1.1 connecting to IpAddress <REDACTED> (1 of 1) for HostName '<REDACTED>' (1 of 1)
[TRACE] ServerSession   Session1.1 connected to IpAddress <REDACTED> for HostName '<REDACTED>' with local Port 8943
[TRACE] ServerSession   Session1.1 server sent AuthPluginName=mysql_native_password
[DEBUG] ServerSession   Session1.1 made connection; ServerVersion=5.5.5-10.5.12-MariaDB-1:10.5.12+maria~buster-log; ConnectionId=345916; Compression=False; Attributes=True; DeprecateEof=True; Ssl=False; SessionTrack=True; Pipelining=True; QueryAttributes=False
[TRACE] ServerSession   Session1.1 creating connection attributes
[TRACE] ConnectionPool  Pool1 returning new Session1.1 to caller; LeasedSessionsCount=1
[TRACE] CommandExecutor Session1.1 ExecuteReader Asynchronous CommandCount: 1
[TRACE] SingleCommandPayloadCreator     Session1.1 Preparing command payload; CommandText: SELECT 1
[TRACE] ServerSession   Session1.1 entering FinishQuerying; SessionState=Querying
[TRACE] ServerSession   Session1.1 returning to Pool1
[TRACE] ConnectionPool  Pool1 receiving Session1.1 back
[INFO]  ConnectionPool  Pool2 creating new connection pool for ConnectionString:<REDACTED>;Connection Timeout=3
[TRACE] ConnectionPool  Pool2 waiting for an available session
[TRACE] ServerSession   Session2.1 created new session
[DEBUG] ConnectionPool  Pool2 no pooled session available; created new Session2.1
[TRACE] ServerSession   Session2.1 connecting to IpAddress <REDACTED> (1 of 1) for HostName '<REDACTED>' (1 of 1)
[TRACE] ServerSession   Session2.1 connected to IpAddress <REDACTED> for HostName '<REDACTED>' with local Port 8947
[TRACE] ServerSession   Session2.1 server sent AuthPluginName=mysql_native_password
[DEBUG] ServerSession   Session2.1 made connection; ServerVersion=5.5.5-10.5.12-MariaDB-1:10.5.12+maria~buster-log; ConnectionId=345920; Compression=False; Attributes=True; DeprecateEof=True; Ssl=False; SessionTrack=True; Pipelining=True; QueryAttributes=False
[TRACE] ServerSession   Session2.1 creating connection attributes
[TRACE] ConnectionPool  Pool2 returning new Session2.1 to caller; LeasedSessionsCount=1
[TRACE] CommandExecutor Session2.1 ExecuteReader Asynchronous CommandCount: 1
[TRACE] SingleCommandPayloadCreator     Session2.1 Preparing command payload; CommandText: SELECT 1
[TRACE] ServerSession   Session2.1 entering FinishQuerying; SessionState=Querying
[TRACE] ServerSession   Session2.1 returning to Pool2
[TRACE] ConnectionPool  Pool2 receiving Session2.1 back
[TRACE] ConnectionPool  Pool1 waiting for an available session
[TRACE] ConnectionPool  Pool1 found an existing session; checking it for validity
[TRACE] ServerSession   Session1.1 ServerVersion=5.5.5-10.5.12-MariaDB-1:10.5.12+maria~buster-log supports reset connection and pipelining; sending pipelined reset connection request
[TRACE] ConnectionPool  Pool1 reaping connection pool
[TRACE] ConnectionPool  Pool1 recovered no sessions
[TRACE] ConnectionPool  Pool2 reaping connection pool
[TRACE] ConnectionPool  Pool2 recovered no sessions
[TRACE] ConnectionPool  Pool1 reaping connection pool
[TRACE] ConnectionPool  Pool1 recovered no sessions
[TRACE] ConnectionPool  Pool2 reaping connection pool
[TRACE] ConnectionPool  Pool2 recovered no sessions
[TRACE] ConnectionPool  Pool1 reaping connection pool
[TRACE] ConnectionPool  Pool1 recovered no sessions
[TRACE] ConnectionPool  Pool2 reaping connection pool
[TRACE] ConnectionPool  Pool2 recovered no `sessions`
[DEBUG] ConnectionPool  Pool2 found Session2.1 to clean up
[TRACE] ServerSession   Session2.1 sending QUIT command
[DEBUG] ServerSession   Session2.1 closing stream/socket
[TRACE] ConnectionPool  Pool1 reaping connection pool
[TRACE] ConnectionPool  Pool1 recovered no sessions
[TRACE] ConnectionPool  Pool2 reaping connection pool
[TRACE] ConnectionPool  Pool2 recovered no sessions
```

**Comment by ertaboy356b** [comment] 2022-10-29 05:32
It stops at this line for a long time: 
```
[TRACE] ConnectionPool  Pool1 found an existing session; checking it for validity
[TRACE] ServerSession   Session1.1 ServerVersion=5.5.5-10.5.12-MariaDB-1:10.5.12+maria~buster-log supports reset connection and pipelining; sending pipelined reset connection request
```
before continuing forward with 'Pool1 reaping connection pool'. It just continue on and on without the program ever breaking from the block.

**Comment by ertaboy356b** [comment] 2022-10-29 05:40
The good news is that the database admin confirms that they will migrate to a newer version during the next maintenance cycle so no big deal if it doesn't get fix. Probably just a bug from that specific version of MaxScale and we do use custom DNS, though in our internal applications we don't use domain names.

**Comment by bgrainger** [comment] 2022-10-29 13:29
> `Session1.1 ServerVersion=5.5.5-10.5.12-MariaDB-1:10.5.12+maria~buster-log supports reset connection and pipelining; sending pipelined reset connection request`

That definitely seems like it's related. Please add `;Pipelining=false` to your connection string. (See https://mysqlconnector.net/troubleshooting/aurora-freeze/ for more information.)

**Comment by ertaboy356b** [comment] 2022-11-01 00:59
Pipelining=False did not do anything. What a weird MaxScale version.

```
[INFO]  ConnectionPool  Pool1 creating new connection pool for ConnectionString: Server=<REDACTED>;Port=<REDACTED>;User ID=<REDACTED>;Database=<REDACTED>;Connection Timeout=3;Pipelining=False
[TRACE] ConnectionPool  Pool1 waiting for an available session
[TRACE] ServerSession   Session1.1 created new session
[DEBUG] ConnectionPool  Pool1 no pooled session available; created new Session1.1
[TRACE] ServerSession   Session1.1 connecting to IpAddress <REDACTED> (1 of 1) for HostName '<REDACTED>' (1 of 1)
[TRACE] ServerSession   Session1.1 connected to IpAddress <REDACTED> for HostName '<REDACTED>' with local Port 13538
[TRACE] ServerSession   Session1.1 server sent AuthPluginName=mysql_native_password
[DEBUG] ServerSession   Session1.1 made connection; ServerVersion=5.5.5-10.5.12-MariaDB-1:10.5.12+maria~buster-log; ConnectionId=380507; Compression=False; Attributes=True; DeprecateEof=True; Ssl=False; SessionTrack=True; Pipelining=False; QueryAttributes=False
[TRACE] ServerSession   Session1.1 creating connection attributes
[TRACE] ConnectionPool  Pool1 returning new Session1.1 to caller; LeasedSessionsCount=1
[TRACE] CommandExecutor Session1.1 ExecuteReader Asynchronous CommandCount: 1
[TRACE] SingleCommandPayloadCreator     Session1.1 Preparing command payload; CommandText: SELECT 1
[TRACE] ServerSession   Session1.1 entering FinishQuerying; SessionState=Querying
[TRACE] ServerSession   Session1.1 returning to Pool1
[TRACE] ConnectionPool  Pool1 receiving Session1.1 back
[INFO]  ConnectionPool  Pool2 creating new connection pool for ConnectionString: Server=<REDACTED>;Port=<REDACTED>;User ID=<REDACTED>;Database=<REDACTED>;Connection Timeout=3;Pipelining=False
[TRACE] ConnectionPool  Pool2 waiting for an available session
[TRACE] ServerSession   Session2.1 created new session
[DEBUG] ConnectionPool  Pool2 no pooled session available; created new Session2.1
[TRACE] ServerSession   Session2.1 connecting to IpAddress <REDACTED> (1 of 1) for HostName '<REDACTED>' (1 of 1)
[TRACE] ServerSession   Session2.1 connected to IpAddress <REDACTED> for HostName '<REDACTED>' with local Port 13539
[TRACE] ServerSession   Session2.1 server sent AuthPluginName=mysql_native_password
[DEBUG] ServerSession   Session2.1 made connection; ServerVersion=5.5.5-10.5.12-MariaDB-1:10.5.12+maria~buster-log; ConnectionId=380508; Compression=False; Attributes=True; DeprecateEof=True; Ssl=False; SessionTrack=True; Pipelining=False; QueryAttributes=False
[TRACE] ServerSession   Session2.1 creating connection attributes
[TRACE] ConnectionPool  Pool2 returning new Session2.1 to caller; LeasedSessionsCount=1
[TRACE] CommandExecutor Session2.1 ExecuteReader Asynchronous CommandCount: 1
[TRACE] SingleCommandPayloadCreator     Session2.1 Preparing command payload; CommandText: SELECT 1
[TRACE] ServerSession   Session2.1 entering FinishQuerying; SessionState=Querying
[TRACE] ServerSession   Session2.1 returning to Pool2
[TRACE] ConnectionPool  Pool2 receiving Session2.1 back
[TRACE] ConnectionPool  Pool1 waiting for an available session
[TRACE] ConnectionPool  Pool1 found an existing session; checking it for validity
[TRACE] ServerSession   Session1.1 ServerVersion=5.5.5-10.5.12-MariaDB-1:10.5.12+maria~buster-log supports reset connection; sending reset connection request
[TRACE] ConnectionPool  Pool1 reaping connection pool
[TRACE] ConnectionPool  Pool1 recovered no sessions
[TRACE] ConnectionPool  Pool2 reaping connection pool
[TRACE] ConnectionPool  Pool2 recovered no sessions
```

**Comment by bgrainger** [comment] 2022-11-01 03:23
> Pipelining=False did not do anything.

Since the hang is coming when MySqlConnector is trying to reset the connection, you could try `; Connection Reset=false` instead. Note that this will leave user-defined variables and temporary tables intact (across multiple calls to `MySqlConnection.Open`) which could cause unexpected behaviour.

> What a weird MaxScale version.

I'm assuming it's passing through the version of the MariaDB 10.5.12 server behind the MaxScale proxy. It has the strange format to try to be compatible with MySQL clients that just parse the first dotted version number.

If that's not actually the version of MariaDB that MaxScale is proxying, then MySqlConnector may be activating incorrect client-side logic based on version-sniffing the connection.

**Comment by ertaboy356b** [comment] 2022-11-03 05:26
I have tried adding the `Connection Reset=False` parameter and it actually crashed. I kinda gave up on it since the migration to MaxScale 7 will be this weekend. Thanks a lot!

```
[INFO]  ConnectionPool  Pool1 creating new connection pool for ConnectionString: Server=<REDACTED>;Port=<REDACTED>;User ID=<REDACTED>;Database=<REDACTED>;Connection Reset=False;Connection Timeout=3;Pipelining=False
[TRACE] ConnectionPool  Pool1 waiting for an available session
[TRACE] ServerSession   Session1.1 created new session
[DEBUG] ConnectionPool  Pool1 no pooled session available; created new Session1.1
[TRACE] ServerSession   Session1.1 connecting to IpAddress <REDACTED> (1 of 1) for HostName '<REDACTED>' (1 of 1)
[TRACE] ServerSession   Session1.1 connected to IpAddress <REDACTED> for HostName '<REDACTED>' with local Port 3357
[TRACE] ServerSession   Session1.1 server sent AuthPluginName=mysql_native_password
[DEBUG] ServerSession   Session1.1 made connection; ServerVersion=5.5.5-10.5.12-MariaDB-1:10.5.12+maria~buster-log; ConnectionId=12973; Compression=False; Attributes=True; DeprecateEof=True; Ssl=False; SessionTrack=True; Pipelining=False; QueryAttributes=False
[TRACE] ServerSession   Session1.1 creating connection attributes
[TRACE] ConnectionPool  Pool1 returning new Session1.1 to caller; LeasedSessionsCount=1
[TRACE] CommandExecutor Session1.1 ExecuteReader Asynchronous CommandCount: 1
[TRACE] SingleCommandPayloadCreator     Session1.1 Preparing command payload; CommandText: SELECT 1
[TRACE] ServerSession   Session1.1 entering FinishQuerying; SessionState=Querying
[TRACE] ServerSession   Session1.1 returning to Pool1
[TRACE] ConnectionPool  Pool1 receiving Session1.1 back
[INFO]  ConnectionPool  Pool2 creating new connection pool for ConnectionString: Server=<REDACTED>;Port=<REDACTED>;User ID=<REDACTED>;Database=<REDACTED>;Connection Reset=False;Connection Timeout=3;Pipelining=False
[TRACE] ConnectionPool  Pool2 waiting for an available session
[TRACE] ServerSession   Session2.1 created new session
[DEBUG] ConnectionPool  Pool2 no pooled session available; created new Session2.1
[TRACE] ServerSession   Session2.1 connecting to IpAddress <REDACTED> (1 of 1) for HostName '<REDACTED>' (1 of 1)
[TRACE] ServerSession   Session2.1 connected to IpAddress <REDACTED> for HostName '<REDACTED>' with local Port 3358
[TRACE] ServerSession   Session2.1 server sent AuthPluginName=mysql_native_password
[DEBUG] ServerSession   Session2.1 made connection; ServerVersion=5.5.5-10.5.12-MariaDB-1:10.5.12+maria~buster-log; ConnectionId=12975; Compression=False; Attributes=True; DeprecateEof=True; Ssl=False; SessionTrack=True; Pipelining=False; QueryAttributes=False
[TRACE] ServerSession   Session2.1 creating connection attributes
[TRACE] ConnectionPool  Pool2 returning new Session2.1 to caller; LeasedSessionsCount=1
[TRACE] CommandExecutor Session2.1 ExecuteReader Asynchronous CommandCount: 1
[TRACE] SingleCommandPayloadCreator     Session2.1 Preparing command payload; CommandText: SELECT 1
[TRACE] ServerSession   Session2.1 entering FinishQuerying; SessionState=Querying
[TRACE] ServerSession   Session2.1 returning to Pool2
[TRACE] ConnectionPool  Pool2 receiving Session2.1 back
[TRACE] ConnectionPool  Pool1 waiting for an available session
[TRACE] ConnectionPool  Pool1 found an existing session; checking it for validity
[TRACE] ConnectionPool  Pool1 returning pooled Session1.1 to caller; LeasedSessionsCount=1
[TRACE] CommandExecutor Session1.1 ExecuteReader Asynchronous CommandCount: 1
[TRACE] SingleCommandPayloadCreator     Session1.1 Preparing command payload; CommandText: set session transaction isolation level repeatable read;
[DEBUG] ServerSession   Session1.1 will cancel CommandId: 4 (CancelledAttempts=1) CommandText: set session transaction isolation level repeatable read;
[DEBUG] MySqlConnection CommandId 4 for Session1.1 has been canceled via command timeout.
[TRACE] ServerSession   Session0.1 created new session
[DEBUG] MySqlConnection Created new non-pooled Session0.1
[TRACE] ServerSession   Session0.1 connecting to IpAddress <REDACTED> (1 of 1) for HostName '<REDACTED>' (1 of 1)
[TRACE] ServerSession   Session0.1 connected to IpAddress <REDACTED> for HostName '<REDACTED>' with local Port 3362
[TRACE] ServerSession   Session0.1 server sent AuthPluginName=mysql_native_password
[DEBUG] ServerSession   Session0.1 made connection; ServerVersion=5.5.5-10.5.12-MariaDB-1:10.5.12+maria~buster-log; ConnectionId=12994; Compression=False; Attributes=True; DeprecateEof=True; Ssl=False; SessionTrack=True; Pipelining=False; QueryAttributes=False
[TRACE] ServerSession   Session0.1 creating connection attributes
[INFO]  ServerSession   Session1.1 canceling CommandId 4 from Session0.1; CommandText: set session transaction isolation level repeatable read;
[DEBUG] ServerSession   Session0.1 canceling CommandId 4 with CommandText KILL QUERY 12973
[TRACE] CommandExecutor Session0.1 ExecuteReader Synchronous CommandCount: 1
[TRACE] SingleCommandPayloadCreator     Session0.1 Preparing command payload; CommandText: KILL QUERY 12973
[TRACE] ServerSession   Session0.1 entering FinishQuerying; SessionState=Querying
[TRACE] ServerSession   Session0.1 sending QUIT command
[DEBUG] ServerSession   Session0.1 closing stream/socket
[DEBUG] ServerSession   Session1.1 setting state to Failed
MySqlConnector.MySqlException (0x80004005): The Command Timeout expired before the operation completed.
 ---> System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at MySqlConnector.Protocol.Serialization.SocketByteHandler.DoReadBytesAsync(Memory`1 buffer) in /_/src/MySqlConnector/Protocol/Serialization/SocketByteHandler.cs:line 89
   at MySqlConnector.Protocol.Serialization.SocketByteHandler.DoReadBytesAsync(Memory`1 buffer) in /_/src/MySqlConnector/Protocol/Serialization/SocketByteHandler.cs:line 98
   at MySqlConnector.Protocol.Serialization.BufferedByteReader.ReadBytesAsync(IByteHandler byteHandler, ArraySegment`1 buffer, Int32 totalBytesToRead, IOBehavior ioBehavior) in /_/src/MySqlConnector/Protocol/Serialization/BufferedByteReader.cs:line 34
   at MySqlConnector.Protocol.Serialization.ProtocolUtility.<ReadPacketAsync>g__AddContinuation|1_0(ValueTask`1 headerBytes, BufferedByteReader bufferedByteReader, IByteHandler byteHandler, Func`1 getNextSequenceNumber, ProtocolErrorBehavior protocolErrorBehavior, IOBehavior ioBehavior) in /_/src/MySqlConnector/Protocol/Serialization/ProtocolUtility.cs:line 423
   at MySqlConnector.Protocol.Serialization.ProtocolUtility.<DoReadPayloadAsync>g__AddContinuation|5_0(ValueTask`1 readPacketTask, BufferedByteReader bufferedByteReader, IByteHandler byteHandler, Func`1 getNextSequenceNumber, ArraySegmentHolder`1 previousPayloads, ProtocolErrorBehavior protocolErrorBehavior, IOBehavior ioBehavior) in /_/src/MySqlConnector/Protocol/Serialization/ProtocolUtility.cs:line 494
   at MySqlConnector.Core.ServerSession.ReceiveReplyAsyncAwaited(ValueTask`1 task) in /_/src/MySqlConnector/Core/ServerSession.cs:line 955
[DEBUG] ServerSession   Session1.1 setting state to Failed
MySqlConnector.MySqlException (0x80004005): The Command Timeout expired before the operation completed.
 ---> System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at MySqlConnector.Protocol.Serialization.SocketByteHandler.DoReadBytesAsync(Memory`1 buffer) in /_/src/MySqlConnector/Protocol/Serialization/SocketByteHandler.cs:line 89
   at MySqlConnector.Protocol.Serialization.SocketByteHandler.DoReadBytesAsync(Memory`1 buffer) in /_/src/MySqlConnector/Protocol/Serialization/SocketByteHandler.cs:line 98
   at MySqlConnector.Protocol.Serialization.BufferedByteReader.ReadBytesAsync(IByteHandler byteHandler, ArraySegment`1 buffer, Int32 totalBytesToRead, IOBehavior ioBehavior) in /_/src/MySqlConnector/Protocol/Serialization/BufferedByteReader.cs:line 34
   at MySqlConnector.Protocol.Serialization.ProtocolUtility.<ReadPacketAsync>g__AddContinuation|1_0(ValueTask`1 headerBytes, BufferedByteReader bufferedByteReader, IByteHandler byteHandler, Func`1 getNextSequenceNumber, ProtocolErrorBehavior protocolErrorBehavior, IOBehavior ioBehavior) in /_/src/MySqlConnector/Protocol/Serialization/ProtocolUtility.cs:line 423
   at MySqlConnector.Protocol.Serialization.ProtocolUtility.<DoReadPayloadAsync>g__AddContinuation|5_0(ValueTask`1 readPacketTask, BufferedByteReader bufferedByteReader, IByteHandler byteHandler, Func`1 getNextSequenceNumber, ArraySegmentHolder`1 previousPayloads, ProtocolErrorBehavior protocolErrorBehavior, IOBehavior ioBehavior) in /_/src/MySqlConnector/Protocol/Serialization/ProtocolUtility.cs:line 494
   at MySqlConnector.Core.ServerSession.ReceiveReplyAsyncAwaited(ValueTask`1 task) in /_/src/MySqlConnector/Core/ServerSession.cs:line 955
   at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 43
[TRACE] ServerSession   Session1.1 entering FinishQuerying; SessionState=Failed
[TRACE] ServerSession   Session1.1 returning to Pool1
[TRACE] ConnectionPool  Pool1 receiving Session1.1 back
[INFO]  ConnectionPool  Pool1 received invalid Session1.1; destroying it
[TRACE] ServerSession   Session1.1 sending QUIT command
[DEBUG] ServerSession   Session1.1 closing stream/socket
```

**Comment by bgrainger** [comment] 2022-11-03 15:06
A "Command Timeout" `MySqlException` is what I'd expect if the server isn't responding. At this point I'm not sure how to diagnose further.

I'm closing the issue for now, but please reopen it if there are still problems with the latest version of MaxScale.

**Closed by bgrainger** 2022-11-03 15:06 UTC
