### ISSUE TITLE
Application Crash When Connecting to MySQL Server After Upgrading to MySqlConnector 8.1/8.2

### ISSUE THREAD

**Issue by engahmedtaha** [mysql-net/MySqlConnector#1423] opened 2023-12-22 20:10 UTC
**Software versions**
MySqlConnector version: 8.2
Server type MySQL version: 8.0.33.0
.NET version:  4.8

**Describe the bug**
I am experiencing an issue where my application crashes without any exception messages when attempting to connect to the MySQL server. This occurs intermittently, and I am unable to capture any specific error information even with try-catch blocks.

**Exception**
No Exception

**Code sample**

```vb.net

Try
    
  con.Open()

Catch ex As MySqlException

    msgbox(ex.Message)  

Catch ex As Exception

    msgbox(ex.Message)  

end try

```

**Expected behavior**
Catching an Exception

**Additional context**
this only happened after upgrading to MySqlConnector version 8.2 or maybe after 8.1
I can test it only if my internet connection is weak

**Comment by engahmedtaha** [comment] 2023-12-22 20:40
sorry it was for the official .net connector

**Comment by bgrainger** [comment] 2023-12-23 15:53
Duplicate of https://bugs.mysql.com/bug.php?id=113501.

**Closed by bgrainger** 2023-12-23 15:53 UTC
