### ISSUE TITLE
Need Help Error Occurred - Connect Timeout expired. All pooled connections are in use. The operation was canceled.

### ISSUE THREAD

**Issue by firephantomassasin** [mysql-net/MySqlConnector#815] opened 2020-05-09 16:44 UTC
Hi,

We are using the mysql connector library v0.65, (sync approach), we have just saw our logs that there are several errors, and this is the error message:

Connect Timeout expired. All pooled connections are in use. The operation was canceled.

![image](https://user-images.githubusercontent.com/8090574/81479625-e2e93b00-9256-11ea-8531-59d9a1ad61c7.png)

Call Stack:

MySql.Data.MySqlClient.MySqlException:
   at MySql.Data.MySqlClient.MySqlConnection+<CreateSessionAsync>d__109.MoveNext (MySqlConnector, Version=0.65.0.0, Culture=neutral, PublicKeyToken=d33d3e53aa5f8c92MySqlConnector, Version=0.65.0.0, Culture=neutral, PublicKeyToken=d33d3e53aa5f8c92: /_/src/MySqlConnector/MySql.Data.MySqlClient/MySqlConnection.csMySqlConnector, Version=0.65.0.0, Culture=neutral, PublicKeyToken=d33d3e53aa5f8c92: 670)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
   at MySql.Data.MySqlClient.MySqlConnection+<OpenAsync>d__25.MoveNext (MySqlConnector, Version=0.65.0.0, Culture=neutral, PublicKeyToken=d33d3e53aa5f8c92MySqlConnector, Version=0.65.0.0, Culture=neutral, PublicKeyToken=d33d3e53aa5f8c92: /_/src/MySqlConnector/MySql.Data.MySqlClient/MySqlConnection.csMySqlConnector, Version=0.65.0.0, Culture=neutral, PublicKeyToken=d33d3e53aa5f8c92: 327)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
   at MySql.Data.MySqlClient.MySqlConnection.Open (MySqlConnector, Version=0.65.0.0, Culture=neutral, PublicKeyToken=d33d3e53aa5f8c92MySqlConnector, Version=0.65.0.0, Culture=neutral, PublicKeyToken=d33d3e53aa5f8c92: /_/src/MySqlConnector/MySql.Data.MySqlClient/MySqlConnection.csMySqlConnector, Version=0.65.0.0, Culture=neutral, PublicKeyToken=d33d3e53aa5f8c92: 285)
   at Investagrams.Data.SqlFactory.SqlParent.ExecuteQuery (Investagrams.Data, Version=1.1.0.0, Culture=neutral, PublicKeyToken=nullInvestagrams.Data, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null: C:\Projects\Investagrams Web\Investagrams\Investagrams.Data\SqlFactory\CommonFactory\SqlParent.csInvestagrams.Data, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null: 205)
Inner exception System.OperationCanceledException handled at MySql.Data.MySqlClient.MySqlConnection+<CreateSessionAsync>d__109.MoveNext:
   at System.Threading.SemaphoreSlim.Wait (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
   at System.Threading.SemaphoreSlim.Wait (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
   at MySqlConnector.Core.ConnectionPool+<GetSessionAsync>d__10.MoveNext (MySqlConnector, Version=0.65.0.0, Culture=neutral, PublicKeyToken=d33d3e53aa5f8c92MySqlConnector, Version=0.65.0.0, Culture=neutral, PublicKeyToken=d33d3e53aa5f8c92: /_/src/MySqlConnector/Core/ConnectionPool.csMySqlConnector, Version=0.65.0.0, Culture=neutral, PublicKeyToken=d33d3e53aa5f8c92: 44)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
   at System.Threading.Tasks.ValueTask`1.get_Result (System.Threading.Tasks.Extensions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51)
   at MySql.Data.MySqlClient.MySqlConnection+<CreateSessionAsync>d__109.MoveNext (MySqlConnector, Version=0.65.0.0, Culture=neutral, PublicKeyToken=d33d3e53aa5f8c92MySqlConnector, Version=0.65.0.0, Culture=neutral, PublicKeyToken=d33d3e53aa5f8c92: /_/src/MySqlConnector/MySql.Data.MySqlClient/MySqlConnection.csMySqlConnector, Version=0.65.0.0, Culture=neutral, PublicKeyToken=d33d3e53aa5f8c92: 652)

looks like it happened on when calling the open connection. 

It happened so many times for about 2 mins.

![image](https://user-images.githubusercontent.com/8090574/81479668-293e9a00-9257-11ea-9614-efdcb2a05364.png)

![image](https://user-images.githubusercontent.com/8090574/81479934-f5647400-9258-11ea-98f4-fe0b3eb9afd5.png)

This never happened before so far, we are closing our connections properly, all of our data / DB calls are wrap in a try catch finally just like this:

int retry = 0;

            do
            {
                try
                {
                    OpenConnection();

                    return queryFunction();
                }
                catch (Exception ex)
                {
                    retry++;

                    if (retry > ConfigConstant.MAX_RETRIES_SQL)
                    {
                        Logger.LogErrorExceptionOnly(ex, string.Format("Method Name: {0}.", queryFunction.Method.Name));
                        throw ex;
                    }
                    else
                    {
                        Thread.Sleep(40);
                    }
                }
                finally
                {
                    CloseConnection();
                }

            } while (true);

This is our connection string: SERVER=xxxxxx;DATABASE=xxxx;USERID=xxxxx;PASSWORD=xxxxxx;POOLING=true;DEFAULT COMMAND TIMEOUT=10;Connection Timeout=5;charset=utf8mb4;

Any suggestions and recommendations on how to fix and prevent this kind of errors? We are using from .net framework 4.7.2 web api

**Comment by firephantomassasin** [comment] 2020-05-18 02:01
Hello, we are encountering this again like continuous repeating errors and our backend API got hang and freeze. We suspect that the azure storage async is interfering or has something to do with this issue.

This is the code of the azure blob storage download text async:

string result = await blockBlob.DownloadTextAsync();


Inner exception:

![image](https://user-images.githubusercontent.com/8090574/82167320-f8f99a00-98ed-11ea-8467-35fe1e937c5f.png)



Inner exception System.OperationCanceledException handled at Investagrams.Data.SqlFactory.SqlParent+<ExecuteQueryAsync>d__26`1.MoveNext
--
System.Threading.CancellationToken.ThrowOperationCanceledException |   |  
[external code] |   |  
MySqlConnector.Core.ConnectionPool+<GetSessionAsync>d__10.MoveNext | ConnectionPool.cs | 42
[external code] |   |  
MySql.Data.MySqlClient.MySqlConnection+<CreateSessionAsync>d__109.MoveNext | MySqlConnection.cs | 652

Repeating errors:

![image](https://user-images.githubusercontent.com/8090574/82167374-2c3c2900-98ee-11ea-84b4-82fa3598ae8c.png)


We didn't saw any azure storage related errors, all mysql related issues.

When we tried to use the synchronous version of azure blob storage DownloadText:
string result = blockBlob.DownloadText();

Everything works fine again. 


Do you have some recommendations? @bgrainger

**Comment by firephantomassasin** [comment] 2020-05-18 04:24
Just an update, even though we are not using the azure storage, we are still encountering this error

Connect Timeout expired. All pooled connections are in use. The operation was canceled.

Do we need to adjust the max pool size? Is there a maximum pool size? @bgrainger  Thanks.

**Comment by bgrainger** [comment] 2020-05-18 04:44
The default maximum pool size is 100. If you are using more than 100 simultaneous connections, and each one will be open for a long time, you should increase `MaxPoolSize` in your connection string.

**Comment by firephantomassasin** [comment] 2020-05-18 04:46
Alright, i think we are reaching more than 100 simultaneous connections at a time since we are handling thousands of request per second. How can we increase or what is the format to increase the maximum pool size? Is it MaxPoolSize=500;?

**Comment by bgrainger** [comment] 2020-05-18 13:56
Yes, that's right.

**Comment by firephantomassasin** [comment] 2020-05-18 14:36
Alright thanks! We have tried implementing that, will let you know if the issue will stil occur.

**Comment by bgrainger** [comment] 2020-06-27 04:42
This is probably a duplicate of https://github.com/mysql-net/MySqlConnector/issues/836.

A "Command Timeout expired" error can cause connections to be leaked, which will lead to a "Connect Timeout expired" error.

**Closed by bgrainger** 2020-06-27 04:42 UTC
