### ISSUE TITLE
DISTINCT in aggregate can return VARCHAR instead of DATETIME under certain conditions

### ISSUE THREAD

**Issue by lauxjpn** [mysql-net/MySqlConnector#898] opened 2020-10-20 11:44 UTC
We got the following query in one of our tests:

```sql
SELECT `o`.`CustomerID` AS `Key`, MAX(DISTINCT (CASE
    WHEN `o`.`OrderDate` IS NOT NULL THEN `o`.`OrderDate`
END)) AS `Max`
FROM `Orders` AS `o`
GROUP BY `o`.`CustomerID`;
```

We expect the `Max` projection to return a `datetime`.
When we manually run the following script against MySQL, that appears to be the case:

```sql
drop temporary table if exists foo;
create temporary table foo

SELECT `o`.`CustomerID` AS `Key`, MAX(DISTINCT (CASE
    WHEN `o`.`OrderDate` IS NOT NULL THEN `o`.`OrderDate`
END)) AS `Max`
FROM `Orders` AS `o`
GROUP BY `o`.`CustomerID`;

desc foo;
drop temporary table if exists foo;
```

The result is:

Field | Type | Null | Key | Default | Extra
-- | -- | -- | -- | -- | --
Key | char(5) | YES |  |  | NULL
Max | **datetime** | YES |  |  | NULL

However, MySqlConnector retrieves a `ColumnDefinitionPayload` with a `ColumnType` of `VarString` in its `Row.GetDateTime().GetValue()` call, resulting in a `string` (see attached video).

[2020-10-20 13-38-36.zip](https://github.com/mysql-net/MySqlConnector/files/5408382/2020-10-20.13-38-36.zip)

This seems to happen only in this specific query. Is this a MySQL or a MySqlConnector bug?
If it is a MySQL bug, can we just add a `DateTime.TryParse()` or something similar to `Row.GetDateTime()` as a fallback?

**Comment by bgrainger** [comment] 2020-10-20 22:58
What MySQL Server version are you running against?

I will try to recreate this locally but first I'll need to reverse-engineer the `CREATE TABLE` definition. (FWIW if you're able to supply a self-contained repro that only uses ADO.NET/MySqlConnector, that generally makes things faster for me.)

**Comment by bgrainger** [comment] 2020-10-20 23:05
Run the folliowing SQL:

```sql
create table Orders
(
	CustomerID char(5) not null,
    OrderDate datetime null
);
insert into Orders values('ABCDE', '2020-01-01 11:22:33');
```

Run the following C#:

```csharp
using var connection = new MySqlConnection(csb.ConnectionString);
await connection.OpenAsync();

using var command = new MySqlCommand(@"SELECT `o`.`CustomerID` AS `Key`, MAX(DISTINCT (CASE
    WHEN `o`.`OrderDate` IS NOT NULL THEN `o`.`OrderDate`
  END)) AS `Max`
  FROM `Orders` AS `o`
  GROUP BY `o`.`CustomerID`;", connection);
using var reader = command.ExecuteReader();
reader.GetColumnSchema()[1].DataType.Dump(); // System.DateTime -- CORRECT ✔️
while (reader.Read())
{
	reader.GetValue(0).GetType().Dump(); // System.String -- INCORRECT ❌
	reader.GetDateTime(0); // throws exception
}
```

**Comment by bgrainger** [comment] 2020-10-21 03:22
I haven't been able to reproduce this yet (with just MySqlConnector; I haven't tried using Pomelo). Are you able to share a repro using just ADO.NET?

**Comment by lauxjpn** [comment] 2020-10-21 09:24
> What MySQL Server version are you running against?

Sorry, forgot to state that. I am running this against MySQL `8.0.21`.

> I haven't been able to reproduce this yet (with just MySqlConnector; I haven't tried using Pomelo). Are you able to share a repro using just ADO.NET?

Seems not so easy to reproduce from scratch. I am able to reproduce it with your code, if I use the Northwind database:

```c#
using System;
using System.Diagnostics;
using System.IO;
using MySql.Data.MySqlClient;

namespace IssueConsoleTemplate
{
    internal class Program
    {
        private static void Main()
        {
            var csb = new MySqlConnectionStringBuilder()
            {
                Server = "127.0.0.1",
                Port = 3308,
                UserID = "root",
                Database = "MySqlConnectorIssue898"
            };

            SetupDatabase(csb.ConnectionString);

            using var connection = new MySqlConnection(csb.ConnectionString);
            connection.Open();

            using var command = new MySqlCommand(
                @"SELECT `o`.`CustomerID` AS `Key`, MAX(DISTINCT (CASE
    WHEN `o`.`OrderDate` IS NOT NULL THEN `o`.`OrderDate`
  END)) AS `Max`
  FROM `Orders` AS `o`
  GROUP BY `o`.`CustomerID`;", connection);

            using var reader = command.ExecuteReader();
            Debug.Assert(reader.GetColumnSchema()[1].DataType == typeof(DateTime)); // INCORRECT; is System.String
            while (reader.Read())
            {
                Debug.Assert(reader.GetValue(1) is DateTime); // INCORRECT; is System.String

                var getDateTimeThrows = false;
                try
                {
                    var dateTime = reader.GetDateTime("Max"); // THROWS
                }
                catch
                {
                    getDateTimeThrows = true;
                }
                
                Debug.Assert(!getDateTimeThrows); // INCORRECT; getDateTimeThrows == true
            }
        }

        private static void SetupDatabase(string connectionString)
        {
            var csb = new MySqlConnectionStringBuilder(connectionString);
            var targetDatabase = csb.Database;
            csb.Database = "sys";
            csb.DefaultCommandTimeout = (uint) TimeSpan.FromMinutes(3).Seconds;

            using var connection = new MySqlConnection(csb.ConnectionString);
            connection.Open();

            using var command = new MySqlCommand(
                $@"drop database if exists `{targetDatabase}`;
create database `{targetDatabase}`;
use `{targetDatabase}`;" +
                File.ReadAllText(@"E:\Sources\Pomelo.EFCore.MySql-5.0\test\EFCore.MySql.FunctionalTests\Northwind.sql"),
                connection);
            command.ExecuteNonQuery();
        }
    }
}
```

I'll dig a bit deeper to find the minimal scenario to reproduce this issue.

**Comment by lauxjpn** [comment] 2020-10-21 09:43
Okay, got it. The following sample contains the minimal SQL lines to reproduce the issue:

```c#
using System;
using System.Diagnostics;
using MySql.Data.MySqlClient;

namespace IssueConsoleTemplate
{
    internal class Program
    {
        private static void Main()
        {
            var csb = new MySqlConnectionStringBuilder()
            {
                Server = "127.0.0.1",
                Port = 3308,
                UserID = "root",
                Database = "MySqlConnectorIssue898"
            };

            SetupDatabase(csb.ConnectionString);

            using var connection = new MySqlConnection(csb.ConnectionString);
            connection.Open();

            using var command = new MySqlCommand(
                @"SELECT `o`.`CustomerID` AS `Key`, MAX(DISTINCT (CASE
    WHEN `o`.`OrderDate` IS NOT NULL THEN `o`.`OrderDate`
  END)) AS `Max`
  FROM `Orders` AS `o`
  GROUP BY `o`.`CustomerID`;", connection);

            using var reader = command.ExecuteReader();
            Debug.Assert(reader.GetColumnSchema()[1].DataType == typeof(DateTime)); // INCORRECT; is System.String
            while (reader.Read())
            {
                Debug.Assert(reader.GetValue(1) is DateTime); // INCORRECT; is System.String

                var getDateTimeThrows = false;
                try
                {
                    var dateTime = reader.GetDateTime("Max"); // THROWS
                }
                catch
                {
                    getDateTimeThrows = true;
                }
                
                Debug.Assert(!getDateTimeThrows); // INCORRECT; getDateTimeThrows == true
            }
        }

        private static void SetupDatabase(string connectionString)
        {
            var csb = new MySqlConnectionStringBuilder(connectionString);
            var targetDatabase = csb.Database;
            csb.Database = "sys";
            csb.DefaultCommandTimeout = (uint) TimeSpan.FromMinutes(3).Seconds;

            using var connection = new MySqlConnection(csb.ConnectionString);
            connection.Open();

            using var command = new MySqlCommand(
                $@"drop database if exists `{targetDatabase}`;
create database `{targetDatabase}`;
use `{targetDatabase}`;

create table `Orders`
(
    `CustomerID` char(5) not null,
    `OrderDate` datetime null
);

CREATE  INDEX `CustomerID` ON `Orders`(`CustomerID`);

insert into `Orders` values ('ABCDE', '2020-01-01 11:22:33');",
                connection);
            command.ExecuteNonQuery();
        }
    }
}
```

Basically, there needs to be an index on the primary key. It does not matter what type the PK column is. The returned type for the `OrderDate` column will always be `System.String`.

Probably some weird MySQL bug.

**Comment by bgrainger** [comment] 2020-10-21 14:23
Thanks for the detailed investigation! That does indeed seem like a MySQL Server bug; I'll take a look at the returned data on the wire and see if there's any way we can work around it.

**Comment by lauxjpn** [comment] 2020-10-21 15:47
> I'll take a look at the returned data on the wire and see if there's any way we can work around it.

Thanks! If that turns out to not be the case, using `DateTime.TryParse()` as a fallback should be fine.

**Comment by bgrainger** [comment] 2020-10-21 20:11
```sql
SELECT `o`.`CustomerID` AS `Key`, MAX(DISTINCT (CASE
    WHEN `o`.`OrderDate` IS NOT NULL THEN `o`.`OrderDate`
  END)) AS `Max`
  FROM `Orders` AS `o`
  GROUP BY `o`.`CustomerID`;
```

@lauxjpn Why such a complicated expression? According to https://dev.mysql.com/doc/refman/5.7/en/flow-control-functions.html#operator_case:

> The second syntax returns the result for the first condition that is true. If no comparison or condition is true, the result after `ELSE` is returned, or `NULL` if there is no `ELSE` part.

So if `` `o`.`OrderDate` IS NOT NULL`` is true, then `OrderDate` will be returned. But if it's false, there's no `ELSE`, so `NULL` will be returned. In that case, why not just `SELECT MAX(DISTINCT `o`.`OrderDate`)` or `SELECT MAX(`o`.`OrderDate`)` ?

**Comment by bgrainger** [comment] 2020-10-21 21:55
I started writing a bug report but found I could reproduce the issue with `mysql:8.0.21` but not `mysql:8.0.22`. So it looks like it might already be fixed in the latest MySQL Server version; @lauxjpn can you confirm?

**Comment by lauxjpn** [comment] 2020-10-22 04:54
> @lauxjpn Why such a complicated expression? According to https://dev.mysql.com/doc/refman/5.7/en/flow-control-functions.html#operator_case:
> 
> > The second syntax returns the result for the first condition that is true. If no comparison or condition is true, the result after `ELSE` is returned, or `NULL` if there is no `ELSE` part.
> 
> So if `` `o`.`OrderDate` IS NOT NULL `` is true, then `OrderDate` will be returned. But if it's false, there's no `ELSE`, so `NULL` will be returned. In that case, why not just `SELECT MAX(DISTINCT `o`.`OrderDate`)` or `SELECT MAX(`o`.`OrderDate`)` ?

Generally I agree. However, this test is specifically about using a where clause with `DISTINCT` in an aggregate, to make sure it works:

_(From https://github.com/dotnet/efcore/blob/b970bf29a46521f40862a01db9e276e6448d3cb0/test/EFCore.Specification.Tests/Query/NorthwindGroupByQueryTestBase.cs#L2531-L2546)_

```c#
[ConditionalTheory]
[MemberData(nameof(IsAsyncData))]
public virtual Task GroupBy_group_Where_Select_Distinct_aggregate(bool async)
{
    return AssertQuery(
        async,
        ss => ss.Set<Order>()
            .GroupBy(o => o.CustomerID)
            .Select(
                g =>
                    new
                    {
                        g.Key, Max = g.Where(e => e.OrderDate.HasValue).Select(e => e.OrderDate).Distinct().Max(),
                    }),
        elementSorter: e => e.Key);
}
```

The [SQL Server specific test implementation](https://github.com/dotnet/efcore/blob/71223690c754af1ff639dd5c3cb715083d35d5ba/test/EFCore.SqlServer.FunctionalTests/Query/NorthwindGroupByQuerySqlServerTest.cs#L1905-L1915) expects the following SQL to be generated, so our generation should generally be finde, though it could be optimized in our (and also probably the SQL Server) case:

```sql
SELECT [o].[CustomerID] AS [Key], MAX(DISTINCT (CASE
    WHEN [o].[OrderDate] IS NOT NULL THEN [o].[OrderDate]
END)) AS [Max]
FROM [Orders] AS [o]
GROUP BY [o].[CustomerID]
```

---

> I started writing a bug report but found I could reproduce the issue with mysql:8.0.21 but not mysql:8.0.22. So it looks like it might already be fixed in the latest MySQL Server version; @lauxjpn can you confirm?

Yes, seems to be fix as of 8.0.22. The Connector/NET team probably ran into the same issue. Didn't find anything about it in the [release notes](https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-22.html) (though only skimmed them).

**Comment by bgrainger** [comment] 2020-10-22 14:31
> Didn't find anything about it in the release notes (though only skimmed them).

I read through the release notes, too, but didn't find anything that sounded like this particular bug.

> Do you want to implement a workaround for them, or should we just skip the test for all MySQL versions < 8.0.22 and call it a day?

I usually do lean towards implementing workarounds for older versions that are still in production. However, the side-effect of this workaround (I think) would be enabling implicit `string`→`DateTime` conversions for _any_ VARCHAR column, which MySqlConnector generally tends to avoid: https://mysqlconnector.net/tutorials/migrating-from-connector-net/#implicit-conversions

Because of that, and because no "actual" users 😀 have reported this bug, and if you can unblock yourself by upgrading the test DB server to 8.0.22 (or use MariaDB), then I'm inclined to leave this as-is for now.

**Comment by lauxjpn** [comment] 2020-10-22 15:59
> Because of that, and because no "actual" users 😀 have reported this bug, and if you can unblock yourself by upgrading the test DB server to 8.0.22 (or use MariaDB), then I'm inclined to leave this as-is for now.

I am okay with that!

**Closed** 2020-10-22 16:01 UTC
Labels: blocking-partner, can't reproduce
