### ISSUE TITLE
Support .net 6 DateOnly and TimeOnly structures

### ISSUE THREAD

**Issue by danbopes** [mysql-net/MySqlConnector#1232] opened 2022-10-15 18:43 UTC
**Is your feature request related to a problem? Please describe.**
.net added a new [DateOnly and TimeOnly](https://devblogs.microsoft.com/dotnet/date-time-and-time-zone-enhancements-in-net-6/) structs. json.net already supports deserialization, and I think it would be useful to add support in the connector.

**Describe the solution you'd like**

**Describe alternatives you've considered**
I'd like to write a custom converted myself, but the documentation seems lacking. If someone can offer me a workaround in the meantime, without converting to a string, that would be nice.

**Additional context**
> NotSupportedException: Type DateOnly not currently supported. Value: 10/04/2004
MySqlConnector.MySqlBulkCopy.<SendDataReaderAsync>g__WriteValue|28_0(MySqlConnection connection, object value, ref int inputIndex, ref Encoder utf8Encoder, Span<byte> output, out int bytesWritten) in MySqlBulkCopy.cs, line 599

**Comment by bgrainger** [comment] 2022-10-16 01:12
The main support for `DateOnly` and `TimeOnly` was added in https://github.com/mysql-net/MySqlConnector/issues/963.

`MySqlBulkCopy.WriteValue` supports `DateOnly` here: https://github.com/mysql-net/MySqlConnector/blob/0dd5b62021a60dc14e43f05e3888cfb4a3af1c37/src/MySqlConnector/MySqlBulkCopy.cs#L562-L565. This was added in https://github.com/mysql-net/MySqlConnector/issues/1143.

Please make sure you're running MySqlConnector 2.1.7 (or later) on .NET 6.0.

**Comment by bgrainger** [comment] 2022-10-16 01:13
Duplicate of #1143

**Closed by bgrainger** 2022-10-16 01:12 UTC
