### ISSUE TITLE
Change DbDataReader.{GetSchemaTable,GetColumnSchema} to return empty results when there is no resultset

### ISSUE THREAD

**Issue by roji** [mysql-net/MySqlConnector#770] opened 2020-02-09 10:51 UTC
As discussed in dotnet/runtime#509. This would be a small breaking change (so ideally done in the upcoming 2.0.0), which would make these methods more consistent and more usable in the new null-annotated world.

/cc @ajcvickers @bricelam

**Comment by bgrainger** [comment] 2020-02-09 14:21
Duplicate of #744

**Closed by bgrainger** 2020-02-09 14:21 UTC

**Comment by bgrainger** [comment] 2020-02-09 14:23
This has already been implemented in the 0.62.0-beta5 release.

**Comment by roji** [comment] 2020-02-10 14:27
Great, thanks @bgrainger!
