### ISSUE TITLE
Charset

### ISSUE THREAD

**Issue by kwaazaar** [mysql-net/MySqlConnector#161] opened 2017-01-19 10:31 UTC
I just found out that I need the Charset connectionstring option to work correctly from .NET full framework + the Oracle MySql.Data to work with MySql on Linux (AWS RDS in my case). My testcase is as follows:

From .NET I store this string into a mediumtext field (collation 'utf8_general_ci', charset 'utf8'): ŻŹŶŴŲŰŮŬŪŨŦŤŢŠŞŜŚŘŖŔŐŎŌŊŇŅŃŁĿĽĻĹĶĴĮĬĪĨĦĤĢĠĞĜĚĘĖĔĒĐĎČĊĈĆĄĂĀŸÝÜÛÚÙØÖÕÔÓÒÑÏÎÍÌËÊÉÈÇÅÄÃÂ

When querying it back from .NET or when looking at it from WorkBench, it turns out this string is stored: ZZYWUUUUUUTTTŠSSSRRROOO?NNNL?LLLKJIIIIHHGGGGEEEEEÐDCCCCAAAŸÝÜÛÚÙØÖÕÔÓÒÑÏÎÍÌËÊÉÈÇÅÄÃÂ

To get this to work, I need to specify CharSet=utf8; in my connectionstring. Only then will the data be stored correctly.

However, when checking the documentation for MySqlConnector, it explicitly mentions which connectionstring options are supported, and CharSet is not amongst them.

**Comment by bgrainger** [comment] 2017-01-19 17:13
MySqlConnector uses `utf8_mb4` by default, which is a strict superset of `utf8`. Therefore, changing the charset to `utf8` shouldn't change the behaviour you're reporting.

I wrote a quick test to try to reproduce the problem but was unable: https://github.com/mysql-net/MySqlConnector/commit/61554bb8c366951904025082167901fe894ae219

To me, this looks like a UTF-8→Latin1 conversion happening somewhere (probably on insert, and almost certainly outside of MySqlConnector).

Can you insert your original string using MySQL Workbench, then query it back with MySqlConnector? That is, is it only `INSERT` that is causing problems, and not `SELECT`?

What do these queries return?

```
SELECT DEFAULT_CHARACTER_SET_NAME, DEFAULT_COLLATION_NAME
FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = '(your DB name)';

SELECT CCSA.character_set_name FROM information_schema.`TABLES` T,
       information_schema.`COLLATION_CHARACTER_SET_APPLICABILITY` CCSA
WHERE CCSA.collation_name = T.table_collation
  AND T.table_schema = "(your db name)"
  AND T.table_name = "(your table name)";

SELECT character_set_name FROM information_schema.`COLUMNS` 
WHERE table_schema = "(your db name)"
  AND table_name = "(your table name)"
  AND column_name = "(your column name)";
```

**Comment by bgrainger** [comment] 2017-03-21 14:33
Closing after two months without feedback.

**Closed by bgrainger** 2017-03-21 14:33 UTC
Labels: can't reproduce
