### ISSUE TITLE
MySqlDataAdapter.Update significantly slower than Mysql.Data package

### ISSUE THREAD

**Issue by shravan2x** [mysql-net/MySqlConnector#673] opened 2019-08-05 10:32 UTC
As the title suggests, I found that the `MySqlDataAdapter.Update` method in this library is much slower than that of the `Mysql.Data` package. The performance is worse by an order of ~5x.

This package also doesn't seem to support an `MySqlDataAdapter.UpdateAsync` method. Is there a specific reason for this?

This is a (non-working) example of the code I used:
```
Stopwatch sw = Stopwatch.StartNew();
DataTable dt = new DataTable();
dt.Columns.Add(new DataColumn("col1", typeof(uint)));
// more of that ^

foreach (Xyz x in xyzs)
{
    DataRow dr = dt.NewRow();
    dr["col1"]= x.Col1;
    dt.Rows.Add(dr);
}

MyDbContext db = new MyDbContext();
MySqlConnection con = db.Database.GetDbConnection() as MySqlConnection;
if (con.State==ConnectionState.Open)
{
    con.Close();
}
con.Open();

MySqlCommand cmd = new MySqlCommand("INSERT IGNORE INTO mytable(col1) VALUES(@col1);", con);
cmd.UpdatedRowSource=UpdateRowSource.None;
cmd.Parameters.Add("@col1", MySqlDbType.UInt32).SourceColumn = "col1";

MySqlDataAdapter da = new MySqlDataAdapter();
da.InsertCommand= cmd;
da.UpdateBatchSize=100;
int records = await da.UpdateAsync(dt);

Console.WriteLine(sw.ElapsedMilliseconds);
```

**Comment by bgrainger** [comment] 2019-08-05 12:59
> This package also doesn't seem to support an `MySqlDataAdapter.UpdateAsync` method. Is there a specific reason for this?

Yes: the underlying `DbDataAdapter` class doesn't have any async support: https://github.com/dotnet/corefx/issues/20658

The Connector/NET implementation is not async; it's essentially just returning `Task.FromResult(Update(rows))`. MySqlConnector only adds new "Async" methods that have a fully asynchronous implementation.

**Comment by bgrainger** [comment] 2019-08-05 13:51
I'm not immediately able to reproduce any performance difference. (A standalone repro that demonstrates the problem might be helpful.)

How many rows and columns are you updating in your DataTable?

**Comment by bgrainger** [comment] 2019-08-05 16:14
Connector/NET _looks_ like it has code that converts multiple `INSERT` statements (in a batch) into `INSERT INTO x(a, b, c) VALUES(1, 2, 3), (4, 5, 6), ...`: https://github.com/mysql/mysql-connector-net/blob/c3b904644b17390ea49d2389ccd461560748ed75/MySQL.Data/src/command.cs#L875-L877

However, this doesn't work in practice: a packet capture shows that it just concatenates all the `INSERT` statements together into one packet.

MySqlConnector currently sends each command in its own packet. On a high-latency connection, this will cause performance issues. It will be addressed by the new batching support that's currently being added: #675.

**Comment by shravan2x** [comment] 2019-08-05 16:17
@bgrainger Around 100 rows and 10 columns. I'll make a repro when I get a chance.

I'll also try it with batching when that lands. Any ETA?

**Comment by bgrainger** [comment] 2019-08-05 16:24
> Around 100 rows and 10 columns. I'll make a repro when I get a chance.

The performance difference is very likely to be caused by Connector/NET sending 100 `INSERT` statements in 1 packet, but MySqlConnector sending 100 `INSERT` statements in 100 packets. A repro is probably unnecessary at this point.

What's the latency to your MySQL Server?

> I'll also try it with batching when that lands. Any ETA?

It should be in beta "soon"; there are some breaking changes being introduced in the next release so it might bake for a while longer before going stable.

**Comment by shravan2x** [comment] 2019-08-05 19:58
> What's the latency to your MySQL Server?

Around 200ms, so your reasoning makes sense.

> It should be in beta "soon"; there are some breaking changes being introduced in the next release so it might bake for a while longer before going stable.

That's fine - if you push a pre-release on NuGet, I'll be able to test it.

**Comment by bgrainger** [comment] 2019-08-05 22:29
[MySqlConnector 0.57.0-beta5](https://www.nuget.org/packages/MySqlConnector/0.57.0-beta5), which adds batch support to `MySqlDataAdapter`, is available; please do look over the breaking changes in [the release notes](https://mysqlconnector.net/overview/version-history/). (In my testing, it's now faster than Connector/NET; let me know how it works for you.)

**Comment by shravan2x** [comment] 2019-08-06 07:35
@bgrainger Just tried with `0.57.0-beta5` and it seems to be 35% faster than Connector/NET now! Great work!

Could you tell me why this package doesn't support `MySqlDataAdapter.UpdateAsync` (i.e. the async version of update)?

**Comment by bgrainger** [comment] 2019-08-06 14:25
> Could you tell me why this package doesn't support `MySqlDataAdapter.UpdateAsync` (i.e. the async version of update)?

See my previous comment: https://github.com/mysql-net/MySqlConnector/issues/673#issuecomment-518223951

The actual implementation of `Update` is performed by `DbDataAdapter`, which doesn't have an `UpdateAsync` implementation. So the options are:

1. Add an `UpdateAsync` method that runs synchronously. (This seems pointless and misleading to me, but Connector/NET does this.)
2. Take all the `DbDataAdapter.Update` code from CoreFX (about 900 lines?) and port it to async, adding it to `MySqlDataAdapter` (and maybe contributing it upstream).
3. Wait for https://github.com/dotnet/corefx/issues/20658 to be implemented, and add the API when `DbDataAdapter.UpdateAsync` is available.

I've currently chosen option 3. (And it looks like npgsql and Microsoft.Data.SqlClient have too.) I'm open to 2 if someone does the work and opens a PR, but it's not work I'm planning to do. (There are no ADO.NET libraries that actually have an async `Update` implementation AFAIK, so I don't consider it a critical issue. I understand it's a Connector/NET API compatibility issue, but I've also decided not to be 100% compatible and this is one of the places where it's incompatible by design. But it was missing from the docs, so I'll add it.)

**Comment by bgrainger** [comment] 2019-08-06 14:59
> But it was missing from the docs, so I'll add it.

Added here: c5bdd60cfa48e00810867838d6de65a493dc2940.

https://mysqlconnector.net/tutorials/migrating-from-connector-net/#mysqldataadapter

**Comment by shravan2x** [comment] 2019-08-07 04:46
> See my previous comment: #673 (comment)

I had somehow missed that entire comment, my bad!

> I've currently chosen option 3.

I think that's reasonable. It isn't urgent on my end either, just one of those nags.

Feel free to close the issue at this point. Could you tell me what's blocking the release version of 0.57.0? Is it simply to wait and test for bugs?

**Comment by bgrainger** [comment] 2019-08-07 15:31
There are a few more batching features I'd like to implement first as part of the initial release (of 0.57.0) and the release needs to be coordinated with Pomelo.MySQL.EFCore (due to a breaking change).

**Closed by bgrainger** 2019-08-07 15:31 UTC
Labels: performance

**Comment by mrogunlana** [comment] 2022-01-28 11:21
@bgrainger this issue seems to still be a problem in the latest version of `MySqlConnector` (re: https://github.com/mrogunlana/Panama.Core/issues/15), hopefully, it's due to a user error on my part, if you're interested in some context of how I implemented the adapter using `MySqlConnector`, please see: https://github.com/mrogunlana/Panama.Core/blob/40d6e16a2fc2cdb97bbf56023b75ec913aadef9a/Panama.MySql.Dapper/MySqlQuery.cs#L574 

I've updated the `MySqlDataAdapter` since then to use `MySql.Data` here temporarily here: https://github.com/mrogunlana/Panama.Core/blob/master/Panama.MySql.Dapper/MySqlQuery.cs#L568 it's essentially the same code, but it's out performing `MySqlConnector` by a very high margin e.g. `MySqlConnector` currently benchmarks at 50K rows at around 10 minutes whereas `MySql.Data` runs a full 100k around 1 minute.

Any ideas/guidance here would be much appreciated!
