### ISSUE TITLE
I have tried to update the latest .net 6 (6.0.35) and still get the same error . just we have Windows Defender as anti virus...

### ISSUE THREAD

**Issue by shajiltetherfi** [mysql-net/MySqlConnector#1520] opened 2024-10-21 06:34 UTC
I have tried to update the latest .net 6 (6.0.35) and still get the same error . just we have Windows Defender as anti virus...

can you please re-open and help to check this problem

![image](https://github.com/user-attachments/assets/ab96d3dc-5c19-40a4-a598-276dc43d5e96)

_Originally posted by @shajiltetherfi in https://github.com/mysql-net/MySqlConnector/issues/1519#issuecomment-2425692317_

**Comment by shajiltetherfi** [comment] 2024-10-21 09:45
@bgrainger  I feel this is not an environmental issue or anti-virus problem, I have downgraded to 2.3.6 -> 2.1.9  and it is working now .. which means it is broken from  2.1.9 ->  2.3.6.

**Comment by bgrainger** [comment] 2024-10-21 16:26
Please keep comments on the original issue #1519 instead of creating duplicates.

**Comment by bgrainger** [comment] 2024-10-21 16:26
Duplicate of #1519

**Closed by bgrainger** 2024-10-21 16:26 UTC
