### ISSUE TITLE
No connection possible on VSCode Ubuntu/Linux

### ISSUE THREAD

**Issue by HerzogVolpe** [mysql-net/MySqlConnector#1170] opened 2022-04-30 22:18 UTC
sorry for the general title, but i just couldnt be more specific

**Software versions**
MySqlConnector version: 2.1.8
Server type (MySQL, MariaDB, Aurora, etc.) and version: MariaDB
.NET version: 5.0.407
(Optional) ORM NuGet packages and versions: 

**Describe the bug**
When used on Ubuntu/Linux it cant connect to my database.
The same code works on Windows 10.
I create the project simply with
dotnet new console
add the package with
dotnet add package MySqlConnector --version 2.1.8
and run my project using
dotnet run

**Exception**
Exception has occurred: CLR/MySqlConnector.MySqlException
An unhandled exception of type 'MySqlConnector.MySqlException' occurred in System.Private.CoreLib.dll: 'Couldn't connect to server'
 Inner exceptions found, see $exception in variables window for more details.
 Innermost exception 	 System.IO.IOException : Cannot determine the frame size or a corrupted frame was received.
   at System.Net.Security.SslStream.<ReceiveBlobAsync>d__172`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at System.Net.Security.SslStream.<ForceAuthenticationAsync>d__171`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at System.Net.Security.SslStream.ProcessAuthentication(Boolean isAsync, Boolean isApm, CancellationToken cancellationToken)
   at System.Net.Security.SslStream.AuthenticateAsClient(SslClientAuthenticationOptions sslClientAuthenticationOptions)
   at MySqlConnector.Core.ServerSession.<InitSslAsync>d__102.MoveNext() in /_/src/MySqlConnector/Core/ServerSession.cs:line 1493
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at MySqlConnector.Core.ServerSession.<ConnectAsync>d__83.MoveNext() in /_/src/MySqlConnector/Core/ServerSession.cs:line 521

**Code sample**
using System;
using MySqlConnector;

namespace MySqlConnectorTest
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello MySqlConnector!");
            MySqlConnection conn = new MySqlConnection("host=d3da53f.online-server.cloud;port=3306;user id=testuser;password=testpassword;database=test_database");
            MySqlCommand cmd = new MySqlCommand("SELECT * FROM testtable",conn);

            conn.Open();
            Console.WriteLine(cmd.ExecuteScalar());
            conn.Clone();
        }
    }
}

**Expected behavior**
I expected it to download the selected table and display the first cell(execute scalar)

**Additional context**
I wonder why it does work on windows but not on linux.
tbh i think i am doing something terribly wrong, but i just cant figure out what.
I added a folder with an example project, the server exists and is online, so feel free to use my database to execute the code.
[TestLinuxMySqlConnector.zip](https://github.com/mysql-net/MySqlConnector/files/8597902/TestLinuxMySqlConnector.zip)

Thanks in advance.

**Comment by bgrainger** [comment] 2022-05-01 16:44
Probably a duplicate of https://github.com/mysql-net/MySqlConnector/issues/1003 and https://github.com/mysql-net/MySqlConnector/issues/904.

This is a breaking change in .NET 5.0: https://docs.microsoft.com/en-us/dotnet/core/compatibility/cryptography/5.0/default-cipher-suites-for-tls-on-linux

You can work around it by specifying the TLS Cipher Suites to use in the connection string, e.g., `;TLS Cipher Suites = TLS_DHE_RSA_WITH_AES_256_GCM_SHA384`.

If you can establish a connection with some other client, run `SHOW SESSION STATUS LIKE 'Ssl_cipher';` to see which cipher it's using (and that you can use in your connection string).

**Comment by bgrainger** [comment] 2022-05-01 16:45
Duplicate of #1003

**Closed by bgrainger** 2022-05-01 16:44 UTC

**Comment by HerzogVolpe** [comment] 2022-05-02 14:40
I executed the command and it returned Ssl_cipher = ""

![grafik](https://user-images.githubusercontent.com/56998323/166253019-e5a7aeaf-fb4d-4924-9d3a-b16879179d83.png)

I guess that means that i am not using a cipher for my connection.
Since the database and the server will be on the same machine, can i somehow allow an encryptionless connection?

**Comment by bgrainger** [comment] 2022-05-03 04:47
Yes; set `SSL Mode = None;` in the connection string.

**Comment by HerzogVolpe** [comment] 2022-05-03 05:22
Thank you!
It works now.
