### ISSUE TITLE
Fail to update Schema Update

### ISSUE THREAD

**Issue by Gyyone** [mysql-net/MySqlConnector#1287] opened 2023-02-24 15:32 UTC
**Software versions**
MySqlConnector version: 2.2.5
MariaDB 10.5
.NET version:   .net 6

**Describe the bug**
First time It will create all the Table and Columns in Blank Database. Second time with Schema update on new Field Will throw the following Exception

**Exception**

```
System.ArgumentException: Invalid collection name: 'Foreign Keys'. (Parameter 'collectionName')
   at MySqlConnector.Core.SchemaProvider.GetSchemaAsync(IOBehavior ioBehavior, String collectionName, String[] restrictionValues, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/SchemaProvider.g.cs:line 75
   at MySqlConnector.MySqlConnection.GetSchema(String collectionName, String[] restrictionValues) in /_/src/MySqlConnector/MySqlConnection.cs:line 602
   at NHibernate.Dialect.Schema.AbstractTableMetadata.InitForeignKeys(IDataBaseSchema meta)
   at NHibernate.Dialect.Schema.AbstractTableMetadata..ctor(DataRow rs, IDataBaseSchema meta, Boolean extras)
   at NHibernate.Dialect.Schema.MySQLDataBaseSchema.GetTableMetadata(DataRow rs, Boolean extras)
   at NHibernate.Tool.hbm2ddl.DatabaseMetadata.GetTableMetadata(String name, String schema, String catalog, Boolean isQuoted)
   at NHibernate.Cfg.Configuration.GenerateSchemaUpdateScript(Dialect dialect, IDatabaseMetadata databaseMetadata)
   at NHibernate.Tool.hbm2ddl.SchemaUpdate.Execute(Action`1 scriptAction, Boolean doUpdate)
```

**Code sample**

```csharp
/* A concise code sample to reproduce the bug */
  public class SessionFactory
    {
        const string versionPath = "assemblyversion.json";
        public static ISessionFactory InitMySQL(string host, string dbname, string port, string userid, string password, params Assembly[] assemblys)
        {
            JsonWorker.Configure(x => {
                x.ContractResolver = new DefaultContractResolver()
                {
                    NamingStrategy = new Newtonsoft.Json.Serialization.DefaultNamingStrategy()
                };
            });
            string ConnectionStr = $"Server={host};Port={port};Uid={userid};Pwd={password};Database={dbname};";
            return InitMySQL(ConnectionStr, assemblys.Length > 0 ? assemblys : new Assembly[] { System.Reflection.Assembly.GetExecutingAssembly() });
        }

        public static ISessionFactory InitMySQL(string connectionStr, params Assembly[] assemblys)
        {
            Dictionary<string, string> pattern = connectionStr.FindPattern(@"(?<strdb>((?i)Database)\s*=\s*(?<dbname>[\w]+)\;*)");
            if (pattern.ContainsKey("dbname"))
            {
                string masterconnectionstr = connectionStr.Replace(pattern["strdb"], "");
                using (MySqlConnection conn = new MySqlConnection(masterconnectionstr))
                {
                    conn.Open();
                    using (MySqlCommand command = conn.CreateCommand())
                    {
                        command.CommandText = $"CREATE DATABASE IF NOT EXISTS `{pattern["dbname"]}`;";
                        command.ExecuteNonQuery();
                    }
                }
            }
            else
            {
                throw new Exception("Please specify Database of connection string");
            }

            bool updateSchema = false;
            Version version = Assembly.GetExecutingAssembly().GetName().Version;

            Version currentVersion = JsonIO.Load<Version>(versionPath);
            if (version == null || currentVersion.ToString() != version.ToString())
            {
                updateSchema = true;
            }
            JsonIO.Save(versionPath, version);
#if DEBUG
            updateSchema = true;
#endif
            return CreateSession(SessionFactory.CreateMySQLPersistence(connectionStr), updateSchema, assemblys);
        }
        public static IPersistenceConfigurer CreateMySQLPersistence(string connectionStr)
        {
            //HbmSerializer.Default.Validate = true;
            //var cfg = new NHibernate.Cfg.Configuration();
            //cfg.AddInputStream(HbmSerializer.Default.Serialize(System.Reflection.Assembly.GetExecutingAssembly()));
            return MySQLConfiguration.Standard
                 .ConnectionString(connectionStr).Driver<NHibernate.Driver.MySqlConnector.MySqlConnectorDriver>().Dialect<NHibernate.Dialect.MySQL57Dialect>();
        }
        public static IPersistenceConfigurer CreateMSSQL2012Persistence(string connectionStr)
        {
            return MsSqlConfiguration.MsSql2012
                 .ConnectionString(connectionStr);
        }
        public static ISessionFactory CreateSession(IPersistenceConfigurer persistenceConfig, bool UpdateSchema, params Assembly[] assemblys)
        {
            //"Server=192.168.56.1;Port=3306;Uid=sa;Pwd=M@ster5am;Database=testdb;"



            ISessionFactory iSessionFactory = Fluently.Configure()
                 .Database(persistenceConfig)

                 .Mappings(m => {
                     foreach (var assembly in assemblys)
                     {
                         m.FluentMappings.AddFromAssembly(assembly);
                     }
                 })

                 .ExposeConfiguration((config) => {

                     config.SetProperty("adonet.batch_size", "100");
                     new SchemaUpdate(config).Execute(Script, UpdateSchema);
                     //NHibernate Not effective Handle The Update. 
                     //When select also trigger listener
                     //config.AppendListeners(NHibernate.Event.ListenerType.PreInsert, new IPreInsertEventListener[] { new NHListener() });
                     //config.AppendListeners(NHibernate.Event.ListenerType.PreUpdate, new IPreUpdateEventListener[] { new NHListener() });

                 })
                 .BuildSessionFactory();

            return iSessionFactory;

        }
        public static void Script(string script)
        {
            string scriptpath = $"{AppDomain.CurrentDomain.BaseDirectory}Scripts/{DateTime.Now.ToString("yyyyMMdd")}.sql";
            DirectoryHelper.CreateDirectory(scriptpath);
            using (StreamWriter sw = new StreamWriter(scriptpath, true))
            {
                sw.WriteLine(script);
            }
        }


    }
```

**Expected behavior**
It should able to Update new Schema on Database on any new Field Added on Class Entity

**Additional context**
```csharp
/*
Original Working with MySQL Database Community It is working without add Driver And MySQL57Dialect, 
After Switch to MariaDB 10.5, Schema would not work 
*/
        public static IPersistenceConfigurer CreateMySQLPersistence(string connectionStr)
        {
            //HbmSerializer.Default.Validate = true;
            //var cfg = new NHibernate.Cfg.Configuration();
            //cfg.AddInputStream(HbmSerializer.Default.Serialize(System.Reflection.Assembly.GetExecutingAssembly()));
            return MySQLConfiguration.Standard
                 .ConnectionString(connectionStr).Driver<NHibernate.Driver.MySqlConnector.MySqlConnectorDriver>().Dialect<NHibernate.Dialect.MySQL57Dialect>();
        }
```

**Comment by bgrainger** [comment] 2023-02-24 23:24
The `Foreign Keys` schema is not currently supported by MySqlConnector: #375.

I don't know NHibernate well enough to know if there's a way to configure it to work without requesting this information.

**Comment by bgrainger** [comment] 2023-02-24 23:24
Duplicate of #375

**Closed by bgrainger** 2023-02-24 23:24 UTC
