### ISSUE TITLE
MySqlParameter.AppendSqlString does not support Version type

### ISSUE THREAD

**Issue by kendallb** [mysql-net/MySqlConnector#844] opened 2020-07-02 20:12 UTC
It's not clear to me how this is implemented in the Oracle connector, however when we pass in a Version() class as a SQL parameter it renders it as a string. It's possible it simply has a fallback to render using .ToString() on the object, however the current implementation in MySqlConnector simply throws an exception:

```
			else
			{
				throw new NotSupportedException("Parameter type {0} (DbType: {1}) not currently supported. Value: {2}".FormatInvariant(Value.GetType().Name, DbType, Value));
			}

```

So to fix this for better compatibility, you should either add direct support for the Version class, or have a fallback to simply convert to a string using .ToString()?

I was going to add support for this myself in my fork, but when I pulled down the latest code from master it no longer builds with Visual Studio 2017 (can't use 2019 yet as we are stuck with some tools not supported in that version yet). Looks like it might be C#8 or later stuff not supported in 2017. I will have to get 2019 installed as we hope to move to that soon...

**Comment by kendallb** [comment] 2020-07-02 20:13
For now I am just going to convert the value to a string before we pass it in, for the one place we use this.

**Comment by bgrainger** [comment] 2020-07-02 22:24
I believe that Connector/NET just converts any arbitrary value to a string by calling `.ToString()` here: https://github.com/mysql/mysql-connector-net/blob/8.0/MySQL.Data/src/Types/MySqlBinary.cs#L91

I'm not a fan of this, as it's a very common way of introducing locale-specific bugs, and there's no way to provide a custom `IFormatProvider` to change culture-specific formatting.

**Comment by bgrainger** [comment] 2020-07-02 22:26
See previous comments on this here: https://github.com/mysql-net/MySqlConnector/issues/410#issuecomment-353170516

I'm still of the opinion that this is error-prone and has an easy workaround so I'm going to close this as a duplicate of #410.

However, it might be nice to have a "friendlier" exception message that links to documentation and an explanation of the workaround.

**Comment by kendallb** [comment] 2020-07-02 22:34
Well yes, I can easily change my code to do a .ToString() on that parameter when we pass it in and that's what I have done for now. But the problem is binary compatibility with the Oracle connector. Not doing this will lead to subtle bugs that nobody is going to find until runtime, because their code used to work with the Oracle connector and now it crashes out with a runtime exception like we had. Thankfully in our case it was just our DB upgrade code, but I don't yet know what else might crash as we are not yet using MySqlConnector in production. I hope to test that out soon, but for now we have only been testing our development systems.

So while I agree that the implementation of the oracle connector is not particularly good, I think if this project is supposed to be a drop in binary replacement for the Oracle one, runtime errors are a nasty side effect you should avoid. Compile time errors I can deal with (had a couple of those), but it's not nice for something to crash at runtime.

**Comment by bgrainger** [comment] 2020-07-02 23:27
Thanks for choosing to switch to MySqlConnector, and for engaging in advocacy for it to be better; I do want it to serve its users well.

That said... MySqlConnector has pivoted away from its initial goal of being a binary-compatible drop-in replacement for Connector/NET, and now aims to be _better_. In some cases this is achieved by greater stringency, even to the point of choosing consistency with other ADO.NET libraries over Connector/NET. (See more discussion at #824.)

While I hear your point that introducing runtime exceptions in previously-working code is bad, being bug-for-bug compatible with Connector/NET is a non-goal of this project (and the new exceptions may identify subtle bugs in clients, which can now be fixed). As an extreme example, MySqlConnector's correct implementation of async methods (instead of just returning synchronously) could cause code that was "previously working fine" to deadlock, but I hope no one would argue that all the async code should be removed in order to make migrating from Connector/NET to MySqlConnector easier for clients.

There's now quite a long list of changes between Connector/NET and MySqlConnector that are documented at https://mysqlconnector.net/tutorials/migrating-from-connector-net/; I would recommend consulting that page to discover if there might be other compatibility issues.

**Comment by kendallb** [comment] 2020-07-03 01:03
Well for what it's worth, we are now live on MySqlConnector and I do appreciate the desire to make it better than the Oracle one (it's one reason we moved over to it :) ). Async is something we do not currently use in our SQL code (I am honestly on the fence about whether async at the SQL transaction level is going to be a win or not), but at least we have the option now. 

So now that we are live, the only issue we had was the transaction one (some legacy PHP code we have does not set it in the command) so we worked around that and so far, so good. A big part of the reason to move is we are trying to get our legacy PHP .net code running on PeachPie to migrate off Phalanger, which will give us the option to move it all to .net core soon.

But I still do think this is something where the original behavior is likely something you should emulate. I get that your connector does a better job, but it's also something that won't necessarily break anything if the fallback is to simply use .ToString()? Perhaps a compromise would be to do that by default, but have a config option to throw an exception if you would like to know if the fallback ends up being used?

**Comment by bgrainger** [comment] 2021-01-16 22:43
> However, it might be nice to have a "friendlier" exception message that links to documentation and an explanation of the workaround.

This was added in #925.

Closing this issue as I don't think `Version` needs to be natively supported in MySqlConnector. (Since there's no `VERSION` data type in MySQL, it would have to be stored as `VARCHAR`, retrieved as a `string`, and then parsed by the application. It doesn't make sense for the `Version`→`string` conversion to be handled by MySqlConnector but the reverse `string`→`Version` conversion to be handled by the application; the bidirectional conversion logic should live in one place.)

**Closed by bgrainger** 2021-01-16 22:43 UTC

**Comment by kendallb** [comment] 2021-01-16 23:45
Yes there is, people using the Oracle connector and changing to this could easily run into a problem as the behavior is different. A better exception is nice, but it would be nicer if it just worked.

**Comment by bgrainger** [comment] 2021-02-14 02:39
FWIW, found a concrete instance when not implementing Oracle's behaviour (of calling `ToString`) was clearly better: https://github.com/mysql-net/MySqlConnector/issues/410#issuecomment-778711929

**Comment by kendallb** [comment] 2021-02-14 04:36
Good point.
