### ISSUE TITLE
Bulk load in AWS Lambda silently fails

### ISSUE THREAD

**Issue by neilgallagher** [mysql-net/MySqlConnector#490] opened 2018-04-27 13:59 UTC
The bulk load function doesn't seem to work within a .net Core 2.0 Lambda function. I'm using version 0.40 and Ive also tried with version 0.36. If the lambda function is run locally it works fine using the exact same database connection and table . Here is my simplified code with a simple table called TestBulk which has 2 varchar columns Col1 and Col2. count always returns 0

``` c#
			using ( var connection = new MySqlConnection( connectionString ) )
			{
				var bulkLoader = new MySqlBulkLoader( connection )
				{
					Local = true,
					TableName = "TestBulk",
					FieldTerminator = ",",
					LineTerminator = "\r\n",
					FieldQuotationCharacter = '"',
					NumberOfLinesToSkip = 1
				};

				bulkLoader.Columns.Clear();
				bulkLoader.Columns.Add("Col1");
				bulkLoader.Columns.Add("Col2");

				var memStream = new MemoryStream() ;

				bulkLoader.SourceStream = memStream ;

				// Note that mem stream is kept open until bulk load has finished
				using ( var bulkFileWriter = new StreamWriter(memStream) )
				{
					bulkFileWriter.WriteLine("\"Col1\",\"Col2\"") ;
					bulkFileWriter.WriteLine("\"1\",\"2\"") ;
					bulkFileWriter.WriteLine("\"3\",\"4\"") ;

					bulkFileWriter.Flush() ;

					memStream.Position = 0 ;

					int count = bulkLoader.Load();

					Logger.LogInformation($"Loaded {count} items") ;
				}
			}
```

**Comment by bgrainger** [comment] 2018-04-27 15:51
Are you able to enable logging in your lambda function and get the logs? There's not much logging around bulk loading, but they still may show if something's going wrong.

Use `MySqlConnectorLogManager.Provider = new ConsoleLoggerProvider();` or one of the other logging providers documented [here](https://github.com/mysql-net/MySqlConnector/tree/master/docs).

**Comment by bgrainger** [comment] 2018-04-28 15:49
I'm not sure what's going wrong, and I don't have access to an AWS Lambda/RDS instance to try to reproduce the problem. (And even if I did, is there any way to debug a Lambda function to try to understand why it's behaving differently than running it locally?)

**Comment by neilgallagher** [comment] 2018-04-29 15:16
Understand. Just to add that with the increasing popularity of aws lambda / serverless it might be worth setting up a test environment for this. It may well be an AWS bug but could be difficult to convince amazon devs. Within aws mysql is a really popular choice for Rds. I also see bulk loading becoming more used as lambda functions have a max 5 minute run time and getting late large scale data sets into rds becomes a real challenge.

**Comment by bgrainger** [comment] 2022-12-23 18:40
This issue is 4.5 years old; multiple major versions of .NET, MySqlConnector, Aurora, etc. have been released since then. Closing as unlikely to be reproducible as written.

**Closed by bgrainger** 2022-12-23 18:40 UTC
