### ISSUE TITLE
Use a different namespace

### ISSUE THREAD

**Issue by nvivo** [mysql-net/MySqlConnector#189] opened 2017-03-09 15:05 UTC
First of all, great work!

I think this project should use a different namespace. Currently, it's hard to use it in the same project as the original one. I'd like to use this library in project I already have the original MySql.Data + EF, but for a new piece of code I'm migrating out of EF. I cannot remove the old provider yet, and I cannot add this one as the namespaces collide.

Currently, I'll need to create a dummy library to add a reference to this project, just to add some indirection in order to use both connections in the same project. Since its a different project, it should have it's own namespace.

**Comment by VitaliyMF** [comment] 2017-03-09 15:12
@nvivo it is possible to use 2 assemblies that have the same namespace and class names (but different assembly name of course) with `extern alias` C# keyword: 
```
extern alias MySqlConnector;
using MySqlConnectorConnection = MySqlConnector.MySql.Data.MySqlClient.MySqlConnection;
```
In most cases project uses only one mysql connector (official or this one), so I guess your situation is not typical.

**Comment by nvivo** [comment] 2017-03-09 15:16
Holy sh*t. Almost 15 years working with c#, it's the first time I see this. =) thanks.

I'll do that then.

In any case, I still think it's a good idea for the project to have it's own namespace.

**Comment by bgrainger** [comment] 2017-03-13 21:10
The use of `MySql.Data` was a deliberate decision to make this an easy, drop-in replacement for the official connector. For now I'm going to close this as "by design".

**Closed by bgrainger** 2017-03-13 21:10 UTC

**Comment by nvivo** [comment] 2017-03-29 04:02
Just venting out, I'm having a real nightmare trying to use this library in the same project as the old driver due to this namespace issue. By itself, it works great. But once it's in the same project an the oracle driver, lots of strange things start to happen. One of them is that the # of connections open to mysql skyrocketed just by from previously ~120 to +650 for some reason.

It seems that EF starts to use this library automatically once it's loaded in the appdomain due to the same namespace. Not sure how it's choosing one over the other, possibly by load order.

I'll leave this here just as some feedback. I admire this project, and I saw real speed improvements by having async. But having the same namespace as another project is definitely not a good idea.

**Comment by bgrainger** [comment] 2017-04-28 00:45
FWIW I've successfully used Connector/NET alongside MySqlConnector in the same project by using `extern alias`, see https://github.com/mysql-net/MySqlConnector/blob/master/tests/Benchmark/Program.cs#L13-L14

However, I have not used it with EF so I have no experience with how it picks an underlying library to use.

It also may not be a viable solution for .NET Core projects as so far I have been unable to find out how to use aliases with `<PackageReference>` or if it's even possible.

**Comment by tb-mtg** [comment] 2019-10-18 05:55
I know this has been closed but it would be really helpful to re-opening & re-consider changing the namespace to not conflict with the **[MySql.Data](https://www.nuget.org/packages/MySql.Data/)** NuGet package and do away with the need for Aliases.

I thought this is meant to be the free Open-Sourced, MIT-licensed, user-friendly version for access MySql database 

So why not make it easier for people who need to use multiple third party packages that end up referencing both [MySql.Data](https://www.nuget.org/packages/MySql.Data) & [MySqlConnector](https://www.nuget.org/packages/MySqlConnector)?

**Comment by bgrainger** [comment] 2019-10-18 07:10
> So why not make it easier for people who need to use multiple third party packages that end up referencing both MySql.Data & MySqlConnector?

This is generally a bad idea, as you'll end up with multiple connection pools in the same application.

Are there specific libraries you're thinking of that don't have the option of depending on MySqlConnector?

**Comment by MaceWindu** [comment] 2019-10-18 08:02
> It also may not be a viable solution for .NET Core projects as so far I have been unable to find out how to use aliases with `<PackageReference>` or if it's even possible.

You can do it. Check this:

Aliases:
https://github.com/linq2db/linq2db/blob/master/Build/linq2db.Providers.props#L7-L8
Apply:
https://github.com/linq2db/linq2db/blob/master/Tests/Linq/Tests.csproj#L40-L51
