### ISSUE TITLE
Support run-time statistics for a connection.

### ISSUE THREAD

**Issue by sumitdvlp** [mysql-net/MySqlConnector#1137] opened 2022-02-14 18:57 UTC
**Is your feature request related to a problem? Please describe.**

While reading/writing over a connection it would be helpful to get information of how much data has been read or written over a connection, the possibilities of user experience enhancement of this feature are huge.

Sql server has this capability to enable this feature.
https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/sql/provider-statistics-for-sql-server

**Describe the solution you'd like**

We can have implementation where we can set a flag to true/false while making a connection. Connection class can store stats in 
 a dictionary just like in Sql server.

**Describe alternatives you've considered**

**Additional context**

**Comment by bgrainger** [comment] 2022-02-14 19:49
There is an existing suggestion for providing metrics for connection pools (using OpenTelemetry or similar): https://github.com/mysql-net/MySqlConnector/issues/491.

This is similar enough that I'll close it as a duplicate.

Duplicate of #491

**Comment by bgrainger** [comment] 2022-02-14 19:50
Duplicate of #491

**Closed by bgrainger** 2022-02-14 19:49 UTC
